- source/config.js
Sadly, having alias for 'ungit' in .profile file doesn't pass in 'ungit' for $0 of a process.  So my previous test were invalid...
> Adding additional check on non-hyphenated options Fix #487

- clicktests/test.all.js
- clicktests/test.generic.js
- clicktests/test.noheader.js
- components/refreshButton/refreshButton.html
- components/refreshButton/refreshButton.js
- components/refreshButton/refreshButton.less
- components/repository/repository.html
- components/repository/repository.js
- components/staging/staging.html
- components/staging/staging.js
Extension of #502.  Moving refresh button out of staging for no header mode so one can refresh even when there are no files in staging.
Regular: 
No header mode:
> Moving refresh button out of staging for no header mode

- public/source/server.js
Sometime, especially when noHeader, ungit.config is not loaded fast enough and errors out one this line.
> Fix missing ungit.config problem when noHeader

- source/git-api.js
Adding IPv6 localhost address to the test for OS X Yosemite that appears to have made IPv6 default over IPv4 (confirmed on Yosemite 10.10.2 with the use of the node api OS -> os.networkInterfaces).
> Add IPv6 test for localhost ip

- components/staging/staging.js
Related to #534.
instead of closing all prevent duplicate dialog opens when there is one outstanding already.
> #534 do not open dialog when it is already opened

- source/git.js
the double carrot (^) which was introduced in #349 is not required if we use `child_process.spawn`
fixes #541
> fix windows diffs

- source/git-api.js
quotes are not needed when using child_process.spawn
fixes #559
> fix credential helper

- source/git-parser.js
the parser now parses the following uris to http urls:
```
https://github.com/FredrikNoren/ungit.git => https://github.com/FredrikNoren/ungit.git
git@github.com:FredrikNoren/ungit.git => http://github.com/FredrikNoren/ungit.git
git://github.com/FredrikNoren/ungit.git => http://github.com/FredrikNoren/ungit.git
```
this also fixes a bug when the uri contains `http` not at the start of the uri
> support git protocol in urls in submodule parser

- source/server.js
```
2015-05-27T07:34:02.954Z - info: GET /api/fs/exists?path=P%3A%5Cnotexists
Wed, 27 May 2015 07:34:02 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at ungit\source\server.js:310:30
```
> use req.query instead of deprecated req.param in /api/fs/exists

- source/git-api.js
The `/baserepopath` api resulted in an infinite loop on windows because the length of the root path is 3 and not 1.
The fix in https://github.com/FredrikNoren/ungit/pull/540 didn't work because the `isRoot` function would always return `true` if the path length was ***greater*** than 3 (win) or 1 (other). The change was reverted in https://github.com/FredrikNoren/ungit/pull/551.
This fix also checks at the end if `currentPath` is a git directory which allows `subst` git directories on windows to work correctly. (On windows you can create virtual drives which are linked to directories.)
This should now really fix #537, #542
---
~~We could also use [`git rev-parse --show-toplevel`](http://stackoverflow.com/a/957978)~~
> fix baserepopath for windows

- test/spec.git-api.branching.js
- test/spec.git-api.conflict-no-auto-stash.js
- test/spec.git-api.conflict.js
- test/spec.git-api.discardchanges.js
- test/spec.git-api.ignorefile.js
- test/spec.git-api.js
- test/spec.git-api.remote.js
- test/spec.git-api.stash.js
Cleanup the `test-temp-dir*` after the tests are done.
Without this change my temp folder was full of `test-temp-dir*` folders and `test-temp-dir*.gitignore` files.
> cleanup tests after they finished

- components/staging/staging.js
before the dialog was shown but if the refresh event for the staging area was fired while the dialog was open the files would be rendered before the dialog was even closed.
this also removes duplicated code for setting `inRebase`, `inMerge` and `commitMessage*` and also makes sure that the `callback` is only called once it is done.
bug introduced with #549
> fix too many files dialog

- source/git-parser.js
From git 2.4.3 release notes
* The "log --decorate" enhancement in Git 2.4 that shows the commit
at the tip of the current branch e.g. "HEAD -> master", did not
work with --decorate=full.
This fixes issue #580.
> Fix with git 2.4.3, non-detached HEAD, causing log messages hidden problem

- source/git.js
join the `task.commands` values for logging so it is easier to copy and past them into the command prompt
> fix logging git commands

- Gruntfile.js
For browserify-components grunt task, prompt a message if the js is not found in a particular component directory.
This helps people who compile from source to identify a compilation problem, after an old component *.js is deleted, but the directory is left.
> Prompt a message in browserify-component grunt task

- source/git.js
The git process exception are currently never caught, making ungit crash in case of network or GIT server failure. The proposed correction is simply a call to the callback with error, when this happens.
As for the array, it appeared the test can fail, under some odd conditions.
> Catch git spawn exception and better Array type test

- public/vendor/less/bootstrap/glyphicons.less
Remove css font IE fix to fix grunt warning, as ungit does not support IE below 9
> Remove css font IE fix to fix grunt warning

- package.json
Update mocha 2.3.3
Without that, on Windows, some tests failed due to wrong execution order of test cases.
> Update mocha 2.3.3

- clicktests/environment.js
At least for me, intermittent test failures follows after shutdown operation.  And it is possible that ungit's git fetch operation is lagging behind and result in 'git-error' and result in false negative test run.
This was super annoying to track down and confirm but it seems this fix does it.
> Fix intermittent test failures

- bin/ungit
- clicktests/environment.js
- clicktests/test.generic.js
- components/header/header.html
- package.json
- public/index.html
- public/source/main.js
- public/source/server.js
- source/config.js
- source/server.js
- source/ungit-plugin.js
It adds support to run ungit under a specific URL root path like http://host:port/root/path .
This fixes https://github.com/FredrikNoren/ungit/issues/313
On the server side, the basic idea is to add a top level middleware in express that rewrites URLs to remove the root path and then moves forward to other middlewares (that do not need any change).
The socket io version had to be bumped up to better support the root path starting with a slash (http://socket.io/docs/migrating-from-0-9/#configuration-differences)
On the client side, there was quite a few changes to support the concept of a root path.
All the tests are succeeding.
> Support the use of a URL root path

- clicktests/environment.js
- clicktests/test.generic.js
- clicktests/test.remotes.js
part of #629
Distributing rootpaths amongst other tests to speed up test runtime and reduce unnecessary duplicate tests.
> Distributing rootpath amongst tests

- components/graph/git-node.js
- components/graph/graph-graphics.html
One of the problems of the new animation is that inner hollow black circle that appears on a node on click didn't have the mina.elastic animation.  Commit node had elastic animation but it's front layer highlight graphic didn't.  Which really bothered my ADD and OCD.
But recently had an idea to have a nested SVG and animate entire SVG dom instead of individual circle dom and that seems to be a better solution.
> More clever on focus animation

- components/graph/git-graph-actions.js
- components/graph/graph.html
- components/graph/graph.less
One of the problems I see is that ungit can grow horizontally too long when there are many branches, tags or remotes.  So this PR is to add icons to every git actions and expand on mouse over.
Some of the icon choices are questionable but if anybody have better license free icons or svg imgs, please let me know.
(FYI, I'm going wait at least a day before merging my PRs so people can comment on it.)
related: #650
[cherrypick, uncommit, revert]
[push, rebase]
[merge, push, check out, delete]
> Minimizing branch actions with icons

- components/commit/commit.html
> show absolute author date as tooltip in commit nodes

- source/git-promise.js
`fs.isExists()` wasn't given a full proper path and failed to check for correct file
cc: @FredrikNoren 
(I believe this is the only fix needed for next release for current FredrikNoren/Ungit#master)
> Fix git#resolveConflicts() bug

- source/git-parser.js
- test/spec.git-parser.js
This is a more generic parser which does not require keys to be in the correct order.
Also adding some unittests.
---
More information: https://github.com/FredrikNoren/ungit/issues/689#issuecomment-178111189 https://github.com/FredrikNoren/ungit/issues/689#issuecomment-178114940 https://github.com/FredrikNoren/ungit/issues/689#issuecomment-178120923
Fixes #689
> fix git submodule parser to support optional keys

- components/graph/git-node.js
- components/graph/git-ref.js
- components/graph/graph.js
One of the cause of #685 is due to manually registering created git-ref to git-node and it was bit confusing.
We are now only using the logic that automatically associates git-ref to git-node bi-directionally when git-node is assigned to git-ref and not manually configuring association.
(same as #698 but during testing I have delete the branch and it got messy...  (╯°□°）╯︵ ┻━┻  )
> Branch logic fix/refactoring

- CHANGELOG.md
- public/source/server.js
- source/config.js
- source/git-api.js
- source/server.js
Some recent bugreports (#689, #679) contain client- and serverside logs but they do not contain any useful errors.
The main reasons for this are:
1. [JavaScript `Error`s are not serializable with `JSON.stringify`](http://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify) by default
2. The [`jsonResultOrFailProm`](https://github.com/FredrikNoren/ungit/blob/master/source/git-api.js#L112) does not log anything in case of an error
---
The first commit fixes point 1 by implementing `toJSON` on `Error`.
Before an empty object `{}` would be returned now the response includes all fields of an `Error` object such as `message` and `stack`:
```
{"stack":"Error: Test\n    at exports.parseGitSubmodule (P:\\ungit\\source\\git-parser.js:217:19)\n    at …
```
> Log Server Errors

- components/repository/repository.js
- source/git-api.js
- source/git-promise.js
* Properly handling few errors that are not really errors
* More subdued error logging in serverside
* Not using "Unhandled" as often client side is handling it
* Not showing stack trace to reduce humane alertness.
cc: @campersau 
```javascript
> Object.defineProperty(Error.prototype, 'toJSON', {
...   value: function() {
.....     var alt = {};
.....     Object.getOwnPropertyNames(this).forEach(function(key) {
.......       alt[key] = this[key];
.......     }, this);
.....     return alt;
.....   },
...   configurable: true
... });
[Error]
> var m = {a: 1, b: 2}
undefined
> var err = new Error('abc');
undefined
> JSON.stringify(m)
'{"a":1,"b":2}'
> JSON.stringify(err)
'{"stack":"Error: abc\\n    at repl:1:11\\n    at REPLServer.defaultEval (repl.js:252:27)\\n    at bound …
```
> Serverside error handling improvement

- CHANGELOG.md
- source/git-promise.js
Somewhere in the move to a promise based git system, ungit stopped using this config option.  
This changes adds the `maxConcurrentGitOperations` option back.  This change is quite important to me as several repositories only work well with `maxConcurrentGitOperations = 1`.  Without it, ungit complains about `index.lock` files
> Fix maxConcurrentGitOperations

- components/staging/staging.js
- components/staging/staging.less
Conflict during rebase white washes commit message boxes as below.  Decided to do more subtle css background coloring for it.  
This only applies to rebase conflicts not merge conflicts.
> Rebase msg

- README.md
The copyright date in the _README.md_ file should be updated to 2016.
This change is so small I did not bother changing the _CONTRIBUTING.md_ file. I hope this is OK.
> Updated copyright date in README.md

- CHANGELOG.md
- source/config.js
- source/git-promise.js
fix: #515 
related: #707 
Currently there are race condition in several git operations we do.  I fixed one obvious bug in /commit but for others it was more complicated due to work space change triggers "stash and pop" operations and etc.  So I just ended up added retry with random backoff time like any other parallelized systems does... 
Although this bug will be very unlikely to be appear again I have kept the fix from #707 as it is good to limit number of git operations.
> Fix ".lock" file conflicts in parallelized git operations

- CHANGELOG.md
- clicktests/test.generic.js
- components/branches/branches.js
- components/gitErrors/gitErrors.js
- components/graph/git-graph-actions.js
- components/graph/git-node.js
- components/graph/git-ref.js
- components/graph/graph.js
- components/imagediff/imagediff.js
- components/path/path.js
- components/remotes/remotes.js
- components/repository/repository.js
- components/staging/staging.js
- components/stash/stash.js
- components/submodules/submodules.js
- components/textdiff/textdiff.js
- source/git-api.js
- source/git-promise.js
- test/spec.git-api.js
Allows operation at a sub dir of git dir.
i.e. if there is a git directory `/tmp/test`, navigating to any sub dir under `/tmp/test` in ungit should be functional as if one is at `/tmp/test`.
I think this will fix #734 but I'm too lazy to test it... :P maybe I will do it over the weekends... :D
> Allow Ungit to functional under sub dir of a git dir

- components/branches/branches.js
- components/graph/git-graph-actions.js
- components/remotes/remotes.js
- components/submodules/submodules.js
> Warn msg update

- CHANGELOG.md
- Gruntfile.js
- clicktests/test.branches.js
- components/graph/git-graph-actions.js
- components/graph/git-node.js
- components/graph/git-ref.js
- source/config.js
- source/git-api.js
> Autocheckout on branch creation

- CHANGELOG.md
- clicktests/test.generic.js
- source/git-api.js
fixes: #753 
To be honest, I really don't like this one.  one should be able to choose either 1st parent or 2nd parent but this one is hardcoded to parent1.  which is not ideal.  
I almost want to recommend users to moving the ref point instead of reverting.  How do you guys feel?  
(Upon confirmation I will add tests, and change log edit)
cc: @FredrikNoren @Ajedi32 @campersau
> Handle revert merge

- CHANGELOG.md
- package.json
Fix #766: Missing npm as a normal dependency
> Fix #766: Missing npm as a normal dependency

- package.json
If you want to depend on npm, at least let us use the one that ships with node if we can.
Currently, this installs a separate copy of npm just for this package using node 6.3.0
> Loosen npm requirement

- CHANGELOG.md
- bin/ungit
Stop forever child process and exit on sig term.
fix: #763
> handle sigterm. fix: #763

- CHANGELOG.md
- clicktests/environment.js
- clicktests/test.loadAhead.js
- components/graph/graph-graphics.html
- components/graph/graph.js
- components/graph/graph.less
- source/config.js
- source/git-api.js
- source/git-parser.js
- source/git-promise.js
- test/spec.git-api.branching.js
- test/spec.git-api.diff.js
- test/spec.git-api.js
- test/spec.git-api.remote.js
fix: #420
~~Currently, what this fix is doing is that if "head" ref is missing from git.log, it will continuously increase git.log result list until it does.  Effectively always loading active git branch on load.
Now, this is not optimal and not my favorite.  I'm planning on writing more optimized solution as it can be bit slow and little barbaric solution as it is...~~
Added two config flags
* numberOfNodesPerLoad: number of nodes to load for each git.log call
* alwaysLoadActiveBranch: Always load with active checkout branch. ()
When `alwaysLoadActiveBranch=true`, terrible name but not sure what I can call it,  ungit will load checked out node on load by skipping previous nodes untill active checked out node is found for `git.log` call.  
I have also added a cheeky little button where …
> Active branch focused git.log() result.

- CHANGELOG.md
- MERGETOOL.md
- README.md
- components/staging/staging.html
- components/staging/staging.js
- components/staging/staging.less
- source/config.js
- source/git-api.js
This is to address issue #783. 
I have added a new configuration option `"mergeTool"`. Its default value `false` means not to use this feature. Setting this to `true` will launch your default merge tool (as configured in your git config). Setting this to a `string value` will launch the merge tool configured under the given name.
Basically under the hood, it runs the [git mergetool command](https://git-scm.com/docs/git-mergetool) and will only work if you have actually configured it properly. I've found this [stackoverflow](http://stackoverflow.com/questions/426026/git-on-windows-how-do-you-set-up-a-mergetool) discussion that explains how to set up your mergetool. Basically you need to edit your `~/.gitconfig` file or use the CLI.
Here are some more details on what I have added/changed:
* …
> External merge tool support

- CHANGELOG.md
- components/graph/git-node.js
- source/config.js
- source/server.js
This one is kind of random, but I noticed you were using `winston` and it comes with a few features that I thought we would benefit from:
I've added a configuration option `"logLevel"` that allows you to set the level of logging you want to see in the server output console. It is set to `warn` by default, which is actually less logging that it currently does; I figure the majority of users are not developing for ungit and would only care about warning and error messages. You can always set this to `silly` in your local configuration file to get all the logs back.
I've also set `winston` to output log level text using colors.
> Log improvements

- CHANGELOG.md
- components/commit/commit.html
A small improvement concerning commit subjects.
The overwhelming consensus of recommended git commit message formatting is the 50/72 rule ([Exhibit A](http://chris.beams.io/posts/git-commit/), [Exhibit B](https://github.com/erlang/otp/wiki/Writing-good-commit-messages)). Git GUI clients are suggesting the same rules but are not enforcing them.
When browsing certain repos I found that ungit UI breaks down after certain length of the subject line (150+ characters). The idea of this commit is to guide the user to use shorter subject messages by cutting the visible commit subject to 72 characters (being less obtrusive than the suggested 50 limit). The rest of the commit subject is shown as a separate body div when inspecting the commit.
Thoughts? 🙏
> Commit message title limiting to 72

- CHANGELOG.md
- clicktests/test.generic.js
- components/commitdiff/commitdiff.html
- components/commitdiff/commitdiff.js
- components/commitdiff/commitlinediff.js
- components/staging/staging.html
- components/staging/staging.js
- components/textdiff/textdiff.html
- components/textdiff/textdiff.js
- source/config.js
- source/git-api.js
- source/git-promise.js
- add whitespace ignore option for file diffs
- changed diff option buttons to toggle buttons
- Fixed a nasty [bug](https://github.com/FredrikNoren/ungit/pull/791/commits/430c8d8197a41e36c24d8f624e25902c6491dca1) where recycled text diff object continuously add new subscriptions periodically and causing high number of duplicate API calls being made.
> Add whitespace ignore option for file diffs fix: #777

- components/graph/graph.js
fix: #804 
I doubt this will break anything and but I think this should eliminate most of the faulty display issues
before:
after:
> fix branch order for ideological branches

- CHANGELOG.md
- components/commit/commit.js
some editors like visual studio and visual studio code do not add an extra newline character to separate the message title from the body
e.g.: 
```
title
body
```
instead of
```
title
body
```
before:
after:
<sub>Sadly this commit can not be taken as an example because I have amend it with ungit...</sub>
> display complete git message body

- CHANGELOG.md
- components/staging/staging.js
- source/git-promise.js
1. fixes #779 where commit messages gets disregarded after conflict resolution operations 
2. Fixed issues where stale `FileViewModel` object caused problems such as below:
- stale file diff
- persisted patched line selection after patching operations is done.
3. Fixed an issue where patching on some key word file names such as "test"
> Persist commit messages during conflict resolution and refresh file content correctly

- CHANGELOG.md
- components/commit/commit.js
- components/commit/commit.less
- components/graph/git-node.js
> Fix left calculation for node diff box

- source/git-api.js
fixes #820 
There might be an other bug:
What if `.gitignore` changes? Should we also update the state on the server?
<sub><strike>(currently changes to to `.gitignore` file are ignored because of the `startsWith` check)</strike> also fixed with this PR</sub>
> fix to many file change events from file system watchers

- .npmignore
- .travis.yml
- CHANGELOG.md
- CONTRIBUTING.md
- Gruntfile.js
- appveyor.yml
- components/app/app.html
- package.json
- source/server.js
This PR introduces Continuous delivery. Each build on master will be published automatically to npm moving forward. This means that improvements to Ungit will be available to end users at a much earlier time than what we've seen historically.
To make sure end users don't get overwhelmed with "please upgrade" messages only major/minor changes will be advertised in the UI (i.e. patch version will not be advertised).
This PR also bumps the version to 1.0.0 since this a major change in how Ungit is delivered (and I've been looking for an excuse to bump it to 1.0.0 for a while ;) ). Since changes will be automatically delivered moving forward, this change will also release a host of previously unreleased features and fixes on master that were awaiting release.
Fixes #823
Fixes #621
> Continuous delivery

- CHANGELOG.md
- components/commit/commit.js
- package.json
- Solve vase sensitivity for gravatar avatars [resolves #847]
> based on https://en.gravatar.com/site/implement/hash/
> Currently, if I write `Neilkalman@gmail.com` or `neilkalman@gmail.com`, I don't get the same result. I made it so that every email is transformed to lowercase so that md5 will work
> [#847] Fix case sensitivity of email address in gravatar hash

- CHANGELOG.md
- components/app/app.js
- package.json
- source/config.js
This PR adds a config `--ungitVersionCheckOverride` to ignore ungit version checks. It hides the notification message from the client side, and doesn't touch the version check functionality on the server side.
I didn't think this change warranted a new entry in the change log and bumping the patch version, please let me know if you think otherwise.
Fixes https://github.com/FredrikNoren/ungit/issues/851
> Add option to override ungit version check

- CHANGELOG.md
- components/path/path.js
- components/textdiff/textdiff.js
Once diff caching means less network traffic but also means we've lost real time text diff change view as file is altered on the background.
Fixed this via simply adding diff invalidation upon directory change event.
> Realtime diff change

- CHANGELOG.md
- package.json
- source/utils/cache.js
fix: #877
This was a crazy bug and I would definitely need more investigation to confirm but it seems that then blocks that are created after the promise is resolved doesn't get called within ubuntu.  I think that is against A+ promise spec but it has been awhile since I took a look at that...
But what we were doing is that we would cache the promise object and chain the then from there, however for whatever reason ubuntu couldn't chain then functions when promise is already resolved and cache was useless as we weren't able to extract the value.
This fix is to store hard value if cached function result value is a promise.
This is a fun bug and I'm interested in seeing how the OS diff cause this subtle bug...
> Fix cache value being promise in ubuntu

- CHANGELOG.md
- README.md
- package.json
- source/config.js
- source/server.js
fixes: #871
--cliconfigonly works now. Transparent override configs: default -> rc -> argv
Post to /api/userconfig writes in JSON, therefore support ini format can be confusing. 
It would be good if yargs started to support an arbitrary configuration and all of the standard paths as in rc. Then it would be possible to remove the rc dependency
> Fix cli args; Ignore ~/.ungitrc with syntax error

- CHANGELOG.md
- Gruntfile.js
- components/crash/crash.html
- components/crash/crash.js
- components/crash/ungit-plugin.json
- package.json
- public/index.html
- public/source/main.js
Fixed #874
Fixed #888
Fixed #889
Fixed #892
Fixed #893
> Updating crash page with instructions and adblock detection

- CHANGELOG.md
- CONTRIBUTING.md
- components/graph/git-graph-actions.js
- components/graph/git-ref.js
- package.json
Previously this is what happened when checking out origin/somebranch:
- Checkout somebranch
- Move somebranch to origin/somebranch
Now, the opposite happens:
- Move somebranch to origin/somebranch
- Checkout somebranch
The reason this is better is because the "checkout some branch" step often creates unnecessary conflicts with whatever you have in your working directory, that is only conflicts with wherever the branch previously was (not where the origin is).
> Fix checking out remote refs

- CHANGELOG.md
- components/branches/branches.js
- components/graph/git-ref.js
- components/path/path.js
- components/remotes/remotes.js
- components/staging/staging.js
- components/submodules/submodules.js
- package.json
Fix: #933
This is a mistake carrying over from front end promisify effort.  previously, we were doing, API call -> check for error and log if needed -> handle response.  But with the help of promises, we are now doing API call -> handle response -> check for error via catch.  Which means catching and ignoring error we've been doing would result in lost error message, (previously "catch and ignore" was implemented to do something that is in effect of "finally" block.  
This left over hangover from pre promise strategy is now removed.
p.s. Huge shout out to @bakkerthehacker for providing detailed reports, images and logs to help discover my mistake.
> Fix frontend promise implementation ignoring git error

- CHANGELOG.md
- components/stash/stash.html
- components/stash/stash.js
- nmclicktests/spec.stash.js
- package.json
- source/git-api.js
fix: #919 
Changing default stash application from pop to apply.  
Considering pop is destructive in nature and stash drop operation is available, I think it is more sensible to just change pop to apply.
> Change git pop -> apply

- CHANGELOG.md
- components/path/path.html
- package.json
- public/source/main.js
fix: #942
This was error on how we handle autocomplete exceptions when we switched over to promises.
(This probably was the cause of the some of the nightmare tests wasn't able to use [`.type()`](https://github.com/segmentio/nightmare#typeselector-text) API as it triggered autocomplete on some of the invalid paths we have.  Will be fixing those tests later to reflect more realistic click tests.)
@wonson: Thank you for the bug reports!
> fix invalid path input for autocomplete causing front end crash

- components/graph/git-ref.js
- nmclicktests/environment.js
fix: #914 
Going back in time doesn't always means banishing ref within the context of ungit.  However, I did not wanted to do potentially expansive calculations to figure out wether or not branches have common ancestor or potentially other expansive calculations so I relied on timestamp.
I think this is generally a "good enough" solution that fulfills intention of the #914 
But I'm open to criticism
> Alert and confirm when `move` is going back in time

- CHANGELOG.md
- bin/credentials-helper
- package.json
fix: #838
Basically due to how the [config.js](https://github.com/FredrikNoren/ungit/blob/master/source/config.js) is doing initialization validation, spawned [credential-helpr](https://github.com/codingtwinky/ungit/blob/master/bin/credentials-helper) by git process to trigger credential collection died silently without erros being properly logged.  
Solution is to remove those dependencies.  (All deps were for logging and error usage tracking, but the value of those are questionable at best and considering this is a specialized process that is to be spawned by git, we really should keep it skinny as possible.)
FYI, because I forgot how cred helpers work and me simply assuming this bug was due to recent git promise upgrade, this was one of the most exhausting bug that I've worked on while …
> Fix cred helper for remotes

- source/git-promise.js
- test/spec.git-api.discardchanges.js
Add a way to properly disregard submodule changes.
notes:
* "Disregard all" function still doesn't handle submodule changes.  I don't think this is a big problem.
* Added "-f" flag as it didn't work for a "dirty" submodules without commits without that flag.
* will add tests later
* I'm still back and forth on transitioning ungit server to maintain states or not as some of the operations like these can get optimized without doing expansive operations per requests as we do now...
cc: @wonson
> Handle disregarding submodule changes

- public/source/main.js
also fix labels on windows
The repositories were already parsed as json in [app.js](https://github.com/FredrikNoren/ungit/blob/master/components/app/app.js#L19)
> autocomplete: parse repositories from local storage as json

- public/source/main.js
String#replace does only replace the first occurrence. Use regex to replace all.
Before:
`D:\dev_projects\ungit` -> `dev_projects\ungit < D:`
After:
`D:\dev_projects\ungit` -> `ungit < dev_projects < D:`
> fix document title on windows

- CHANGELOG.md
- bin/ungit
- components/remotes/remotes.js
* Fix disabled fetch after a page load bug fix from #1003 
* `forceLaunchPath` is now used to force browser launch at user configured path despite the `launchBrowser` flag.  fix: #1006
> Fetch bug fix and `forceLaunchPath` scope change

- CHANGELOG.md
- components/branches/branches.html
- components/branches/branches.js
- components/graph/git-graph-actions.js
- components/graph/git-ref.js
- components/repository/repository.js
- components/staging/staging.js
- nmclicktests/spec.branches.js
- nmclicktests/spec.load-ahead.js
- nmclicktests/spec.remotes.js
- nmclicktests/spec.submodules.js
- package-lock.json
- package.json
- public/less/styles.less
- source/git-api.js
fixes #966
* ability to list all branches including remote branches within branch list bar.
* lots of refactoring to recycle and share git-ref objects and checkout logic for simplified code path
* ability to checkout remote branches[1]
[1] Current implementation of remote branch logic is something that I'm not sure if it is a good idea always.
Currently, when remote branch checkout is performed, ungit will FORCE move local branch of the remote branch to the remote branch's location and checkout that local branch.  
This is not always ideal and needs to be discussed more and is demonstrated below.
* you can see that remote branch `remot/imgtest` and local `imgtest` branch is in different locations.
* when `remot/imgtest` is checked out, local `imgtest` is force moved to `remot/imgtest`. …
> Add remote branch listing feature

- components/commit/commit.js
Returning an empty object will remove the inline styles completly. No need to set everything back to 0 or inherit.
Not sure when this issue occured the first time.
fixes #1025
> fix commit detail layout while hovering over commit node

- CHANGELOG.md
- components/app/app.js
- components/branches/branches.js
- components/gitErrors/gitErrors.js
- components/graph/git-graph-actions.js
- components/graph/git-node.js
- components/graph/git-ref.js
- components/graph/graph.js
- components/home/home.js
- components/path/path.js
- components/remotes/remotes.js
- components/staging/staging.js
- components/stash/stash.js
- components/submodules/submodules.js
- nmclicktests/environment.js
- package-lock.json
- package.json
fixes #1017 
tldr; I was trying to be clever in handling promise rejections, it introduced intermittent test failures, and I have sloppily fixed it.  Now it is handled manually to be more precise.
----
Each promises calls requires proper catch function to either ignore or handle exceptions.  However, I thought I was being clever by using [`onPossiblyUnhandledRejection`](http://bluebirdjs.com/docs/api/promise.onpossiblyunhandledrejection.html) and this caused some inconsistencies in click tests, especially in windows side, as name suggests, its "possible" not definite.  
So I have sloppily removed it and now here we are manually attaching custom individual catch blocks to all promises, which it bit annoying but I can't think of any other better way.
> handle failed promises

- Gruntfile.js
- nmclicktests/environment.js
- nmclicktests/spec.helper.js
- source/git-api.js
- test/spec.helper.js
The clicktest output is too bloated. This is an attempt to clean it
> Cleanup clicktest output

- nmclicktests/spec.branches.js
on windows clicking on cherry pick which results in conflicts might take some time
hopfully fixes #1043
I observed the same issue as @ylecuyer in #1045 but on my local windows machine.
I tested it serveral times and I only got reliable results with `3000` milliseconds or more with nightmare visible `true` and `false`. Let's see if that works for appveyor.
> wait for cherrypick in tests

- components/staging/staging.js
missed this in https://github.com/FredrikNoren/ungit/pull/1046
It was hard to see with the mixed arrow / normal functions. Maybe we should clean them up...
> fix commit & push with force

- CHANGELOG.md
- components/header/header.less
- package.json
Just a quickie fix I find this more pleasing to my eyes.
> Mover version number below logo with 140px padding

- CHANGELOG.md
- bin/credentials-helper
- package-lock.json
- package.json
This PR fixes #1076.
The problem was that `JSON.parse` was called before all the chunks are fetched from the server.
Therefore the credential helper was printing username and password that are different from the ones typed
in the popup form.
I think this PR also fixes a problem of syntax error during authentication, reported in #1060.
Honestly speaking I don't know why this bug has not been reported. Everyone should've faced this issue?
> Fix credential helper not fetching all the authentication data

- CHANGELOG.md
- components/graph/git-node.js
- package-lock.json
- package.json
- public/source/main.js
fixes #1086
upgrading to `jquery-ui` 1.12 required [some changes to `autocomplete`](https://jqueryui.com/upgrade-guide/1.12/#require-wrappers-for-each-menu-item) and the way to [include the different widgets](https://jqueryui.com/upgrade-guide/1.12/#official-package-on-npm).
> fix missing jquery and jquery ui references

- Gruntfile.js
- components/app/app.js
- components/branches/branches.js
- components/stash/stash.js
- nmclicktests/spec.stash.js
- public/source/main.js
- public/source/storage.js
This change wraps usages of localStorage with a custom storage object so that ungit still works in environments where localStorage is not available. It is not an ideal solution and does not provide the same features as actual localStorage, but is intended to not break.
Background: I am trying to update the [VSCode Ungit extension](https://github.com/Hirse/vscode-ungit) to use the new, better [VSCode WebView API](https://code.visualstudio.com/docs/extensions/webview), but am blocked due to the [missing localStorage support](https://github.com/Microsoft/vscode/issues/52246).
> Wrap localStorage to not depend on it

- CHANGELOG.md
- components/graph/graph.js
- package-lock.json
- package.json
fix: #1139 
Ensure all remote tags are added to ungit, even when they don't have the deref tags.  
(which I'm still not sure how it was induced)
> Ensure addition of remote tags

- components/graph/git-node.js
Selection from the branch search autocomplete fails because `this` is set to the jQuery object, not the class instance:
> Fix branch search box

- CHANGELOG.md
- components/remotes/remotes.js
- package-lock.json
- package.json
When changing remotes using the dropdown in ungit 1.4.35, the following error occurs:
Firefox 64
```
TypeError: this.currentRemote is not a function[Learn More] remotes.js:97
changeRemote remotes.js:97
init/</< knockout:99
dispatch jquery:5182
add/elemData.handle jquery:4991
```
Chrome 69
```
Uncaught TypeError: this.currentRemote is not a function
at Object.changeRemote (remotes.js:97)
at HTMLAnchorElement.<anonymous> (knockout:99)
at HTMLAnchorElement.dispatch (jquery:5183)
at HTMLAnchorElement.elemData.handle (jquery:4991)
```
This issue prevents the user from changing remotes.
> fix changing remotes in remotes dropdown

- components/staging/staging.html
- components/staging/staging.less
Using the glyphicons makes it easier to see the state of the checkbox.
> Use glyphicon for commit amend checkbox

- CHANGELOG.md
- components/app/app.html
- components/app/app.js
- components/gitErrors/gitErrors.html
- components/gitErrors/gitErrors.js
- nmclicktests/environment.js
- package-lock.json
- package.json
- public/index.html
- source/config.js
Related to #1170
Google Analytics is now useless and can be removed
> Remove Google Analytics and sendUsageStatistics

- public/index.html
fixing broken git icons, which occurs when ungit is served from proxy with url rewrite (like datalab does).
#1190 is what I'm trying to address here!
> fixing broken git icons

- CHANGELOG.md
- components/dialogs/dialogs.js
- package-lock.json
- package.json
Improves the textarea of the gitignore Dialog:
* Use the existing `form-control` visual design
* Use monospace font
* Remove spellchecking
* Only allow vertical resizing to prevent growing outside of the dialog
Before:
After:
> Gitignore Dialog style

- source/git-promise.js
Ungit parses git output expecting english.
My default locales configuration is not english so I get a lot of warnings, e.g. when moving a branch.
This PR forces LC_ALL=C before running git commands so the output is always in english.
> force LC_ALL=C when running git

- CHANGELOG.md
- components/textdiff/textdiff.js
- package-lock.json
- package.json
- public/less/d2h.less
Applies `user-select: none;` to `.d2h-code-line-prefix` and `.d2h-code-linenumber` classes.  This allows selection text from diffs for copy and paste without getting line numbers and +/- prefixes.
Closes #1214
> Prevent diff linenumber selection

- bin/ungit
bin/ungit script didn't use config.ungitBindIp like sources/server.js.
On Mac OS, when I type `ungit` command in one terminal, it starts the server and open browser window.
But when I type again in other terminal, it fails with error:
`Error: listen EADDRINUSE: address already in use 127.0.0.1:8449`
lsof shows that server is running on localhost: `TCP localhost:8449 (LISTEN)`
> Ensure bin/ungit to bind to 127.0.0.1

- CHANGELOG.md
- components/header/header.less
- package.json
This PR fixes the header logo width to a constant value.
The width value of the logo image is `15%` now, and it extends the width value of the parent anchor tag (which navigates to the homepage) too big. Eventually, the transparent clickable area is created. 
I fixed the width to 100px to limit the clickable area to the displayed image.
> Fix the width value of the header logo

- .travis.yml
remove old g++ workarounds (looks like they aren't needed. Introduced in  https://github.com/FredrikNoren/ungit/pull/675)
Looks like `libgconf-2-4` is required for running nightmare (electron) clicktests. See https://github.com/electron/electron/issues/1518
Not sure why this wasn't an issue before.
This just took me [16 tries](https://travis-ci.org/campersau/ungit/builds/604400898) 😄
> Add libgconf-2-4 package for nightmare on travis

- components/branches/branches.html
- components/branches/branches.less
- components/remotes/remotes.html
- components/submodules/submodules.html
* Use Octicon (instead of `X`) for removing remotes, submodules, and branches
* Use `external-link` icon for link to submodule-url
* Hide dividers and `Update Submodules` entry when there are no submodules
* Branches-dropdown checkboxes:
* Use Glyphicons checkboxes in branches-dropdown
* Move checkboxes in front of labels
* Add space between labels
> Use consistent icons in dropdown

- components/commit/commit.html
- components/commit/commit.js
- components/commit/commit.less
- components/commitdiff/commitdiff.js
- components/stash/stash.js
* Show the diff buttons only when a commit is selected, but not on hover
* Remove empty space when no commit message body is present
* Align margins in the commit-"card"
* Clean up lint issues in changed files
*Before*
*After*
> Hide diff-buttons on commit hover

- components/stash/stash.html
- public/source/main.js
The buttons in the "Stashed Changes" didn't get the correct tooltips due to a missing class.
This PR also removes the class after tooltips are initialized so they don't get called multiple times.
> Correctly initialize tooltips on stash

- .travis.yml
- appveyor.yml
- package.json
The click tests have been failing for a while on Travis (i.e. on Linux) due to a timeout.
I have tried to get them to run on [AppVeyor Linux](https://ci.appveyor.com/project/Hirse/ungit/builds/28439957), [GitHub Actions](https://github.com/Hirse/ungit/runs/277006406), [Azure Pipelines](https://janpilzer.visualstudio.com/ungit/_build/results?buildId=2), and [CircleCi](https://app.circleci.com/jobs/github/Hirse/ungit/5) but keep running into the same timeout issue.
I was even able to reproduce that using the WSL on my Windows machine.
The click tests pass on locally on Windows as well as on AppVeyor Windows images.
To get the build status back to green this PR restricts Travis to run only the unit tests and extends the build matrix for AppVeyor.
* Add more npm scripts to remove dependency …
> Travis and AppVeyor config

- .gitignore
- Gruntfile.js
Add raven.min.js.map to stop Firefox from issuing a warning.
I mostly did this to reduce the number of warning and be able to better focus on actual issues.
> Add raven.js map file

- source/config.js
Starting ungit with `ungit --authentication` but without adding users leads to bad error messages when trying to login because the user-pw map is not initialized. Setting the config default to an empty map prevents this error.
> Set users config to empty map

- source/git-api.js
- test/spec.git-api.js
Currently it is not possible to remove all content from the .gitignore file as an empty string request is considered invalid by the server.
* Allow empty string requests for gitignore
* Extend test to cover empty string
* Return 400 instead of 500 for invalid requests (not a server issue)
* Fix lint issues in gitignore function
> Enable clearing gitignore file

- source/server.js
Not setting the `resave` and `saveUninitialized` options in the expressjs session is [deprecated](https://github.com/expressjs/session#resave) and leads to warning messages. This PR sets them explicitly to their default values.
> Set value for deprecated default options of expressjs session

- components/branches/branches.html
- components/branches/branches.js
- components/path/path.html
- components/path/path.js
- components/path/path.less
- components/path/ungit-plugin.json
- components/remotes/remotes.html
- nmclicktests/spec.remotes.js
- public/less/generic.less
* Invalid Path
* Use `container` to center the content
* No repository
* Use "git repository" instead of just "repository" to be more precise
* Fix path display string on windows
* Unify panel header and button texts
* Fix checkbox design
* Empty repository
* Remove divider when list of remotes is empty
* Disable branch dropdown when list of refs is empty
* Use default label when there are no commits
For a better view of the changes (without the indentation) use https://github.com/FredrikNoren/ungit/pull/1228/files?w=1
> Improve git-init experience

- source/git-promise.js
- test/spec.git-api.conflict.js
This PR takes the change from #1167 by @ylecuyer and adds a simpler test.
I am using the existing merge-conflict test, which doesn't fit perfectly, but is the only one I found that uses merging.
> Include file diff in merge commits (see #1167)

- components/graph/git-graph-actions.js
- components/graph/graph.html
- components/graph/graph.less
- public/less/styles.less
Even before switching to the latest version of Octicons in #1224 these icons were not showing up for me.
This PR replaces the broken references to the old octicons and glyphicons with the SVG Octicons.
The icons should look the same as before with the exception of the Move icon. Instead of arrows in all directions, the new one points to the target of the move.
Also removes CSS classes for the very old image icons used before #605.
> Restore icons on graph actions using Octicons

- .travis.yml
- CHANGELOG.md
- Gruntfile.js
- appveyor.yml
- package-lock.json
- package.json
based on #1240 this will create a `dist` folder which contains all zipped builds from electron.
These zips are uploaded as artifacts on AppVeyor for every build and can be release by Travis if a commit in the `master` branch is tagged.
Maybe we want to automatically create tags during builds on master which then starts another build which creates the actual release.
fixes https://github.com/FredrikNoren/ungit/issues/1218
fixes https://github.com/FredrikNoren/ungit/issues/1222
> Electron publish

- source/server.js
I guess this was a copy and paste error in https://github.com/FredrikNoren/ungit/commit/543449e16ac83e1635d300c4e66b9121536e815e#diff-71e7385fb3d187340c7741bf6d4f82ffL28-R27
> use process.exit instead of none existing app.quit

- CHANGELOG.md
- package-lock.json
- package.json
- public/main.js
Apparently macOS requires copy & paste menu items in order to copy and paste text from and to applications.
In #1250 I left them out, because I didn't know that at that time.
fixes #1251
> add copy and paste menu items in electron

- CHANGELOG.md
- bin/ungit
- public/main.js
the logic was also different in `bin/ungit` and `public/main.js` (electron)
- `--no-launchBrowser`: browser is never launched
- `--forcedLaunchPath=`: navigates to home screen
- `--forcedLaunchPath=path`: navigates to `/#/repository?path=path`
fixes https://github.com/FredrikNoren/ungit/issues/1259
> check for launchBrowser if ungit is already running

- CHANGELOG.md
- bin/credentials-helper
- components/app/app.js
- components/commitdiff/commitlinediff.js
- components/dialogs/dialogs.js
- components/staging/staging.js
- components/textdiff/textdiff.js
- nmclicktests/environment.js
- nmclicktests/spec.authentication.js
- nmclicktests/spec.discard.js
- public/source/server.js
- source/git-api.js
- source/git-parser.js
- source/git-promise.js
- test/spec.credentials-helper.js
- test/spec.git-api.submodule.js
(also want to check timeouts in appveyor builds)
fixes https://github.com/FredrikNoren/ungit/issues/1265
fixes https://github.com/FredrikNoren/ungit/issues/1266
> remove unused imports, make clicktests more reliable, fix git rev-parse with bare repositories, fix crash when directory gets deleted

- CHANGELOG.md
- package-lock.json
- package.json
- source/git-parser.js
- Diff does not work for first commit [#1124](https://github.com/FredrikNoren/ungit/issues/1124)
- `--no-launchBrowser` is ignored when ungit already running [#1259](https://github.com/FredrikNoren/ungit/issues/1259)
- Bare repositories don't work with git 2.25 [#1265](https://github.com/FredrikNoren/ungit/issues/1265)
- ungit crashes if current directory is deleted [#1266](https://github.com/FredrikNoren/ungit/issues/1266)
- Make clicktests more reliable [#1263](https://github.com/FredrikNoren/ungit/pull/1263)
- Rename + changes only show rename [#1175](https://github.com/FredrikNoren/ungit/issues/1175)
- Remove Node 8 from build matrix [#1256](https://github.com/FredrikNoren/ungit/pull/1256)
> Prepare version 1.5.2

- Gruntfile.js
- package-lock.json
- package.json
- source/git-api.js
- source/sysinfo.js
- test/spec.git-api.submodule.js
Currently, ungit has a dependency on the whole `npm` package, which is only used to check latest versions on the npm registry.
This change replaces `npm` with more light-weight solutions to provide the same functionality.
> Remove dependency on npm

- components/staging/staging.html
- components/staging/staging.less
To be inline with the `ignore` and `discard` buttons.
> Convert patch to button and remove old patch tooltip css

- CHANGELOG.md
- source/config.js
While playing around with github actions I ran into this issue where `npm test` just prints out the command line help from ungit https://github.com/campersau/ungit/runs/474664577?check_suite_focus=true#step:18:14
That's because on macOS the full path is provided as the first argument which contains `ungit` as a folder name:
```js
{ _: [ 'test' ], '$0': '/Users/runner/runners/2.165.2/work/ungit/ungit/node_modules/.bin/grunt' }
```
whereas on linux
```js
{ _: [ 'test' ], '$0': 'node_modules/.bin/grunt' }
```
and windows
```js
{ _: [ 'test' ], '$0': 'node_modules\\grunt\\bin\\grunt' }
```
only the relative path is provided.
> Fix argument check for macOS

- CHANGELOG.md
- components/textdiff/textdiff.html
- components/textdiff/textdiff.js
Fixes performance issues with `signal` and should use less memory.
This is the PR for one of my proposals from https://github.com/FredrikNoren/ungit/issues/1091#issuecomment-586589079
> Change how textdiff settings changes are handled

- CHANGELOG.md
- components/graph/git-node.js
- components/graph/graph.html
- nmclicktests/environment.js
- public/source/knockout-bindings.js
- The focus handling when creating a new branch or tag wasn't very user friendly because the form go closed after the name input lost focus + 200ms. E.g. using the keyboard to tab through the buttons wasn't possible and also sometimes a direct click wasn't recognised because of the losing focus.
- The branching form now is a form again so it is possible to create branches by just pressing enter. It got lost during the refactoring in https://github.com/FredrikNoren/ungit/pull/630
- The clicktest has been updated to use a custom `insert` and `click` function because the standard nightmare methods call blur methods which interfered with the focus logic. This was reliable reproduceable on macOS: [before](https://github.com/campersau/ungit/runs/474826569?check_suite_focus=true#step:19:331) …
> Better focus handling when creating branches and tags

- CHANGELOG.md
- components/graph/git-node.js
- components/graph/graph.js
This code for updating the author date after some time wasn't called any more
https://github.com/FredrikNoren/ungit/blob/4147fd0eba9622731032475116d7105196ad8765/components/commit/commit.js#L71-L82
Because `updateAnimationFrame` was removed from `git-node` and `graph` in https://github.com/FredrikNoren/ungit/pull/630 which wasn't noted because of this check
https://github.com/FredrikNoren/ungit/blob/4147fd0eba9622731032475116d7105196ad8765/components/repository/repository.js#L54
Since updating the author date is the **only** thing that is done inside of [`window.requestAnimationFrame`](https://github.com/FredrikNoren/ungit/blob/4147fd0eba9622731032475116d7105196ad8765/public/source/main.js#L182-L190) we could also consider changing it to a `setTimeout`.
> Update author date again

- .travis.yml
- CHANGELOG.md
- package-lock.json
- package.json
- Bump dependencies [#1283](https://github.com/FredrikNoren/ungit/pull/1283)
- Running npm scripts on macOS [#1287](https://github.com/FredrikNoren/ungit/pull/1287)
- Reduce CPU and Memory consumption in textdiff. Addresses part of [#1091](https://github.com/FredrikNoren/ungit/issues/1091)
- Better focus handling when creating branches and tags [#1288](https://github.com/FredrikNoren/ungit/pull/1288)
- Don't show error page when reloading the page [#1289](https://github.com/FredrikNoren/ungit/issues/1289)
- Periodically update author date of commits again [#1286](https://github.com/FredrikNoren/ungit/pull/1286)
Since some of the issues were found on macOS I am going to enable osx tests on travis. I have also prepared everything for windows tests on travis but commented it out for now.
> Prepare version 1.5.5

- .github/workflows/bump.yml
This will run our `bumpdependencies` grunt task every day and if the dependencies have changed automatically create a PR with the updated dependency versions.
Example: https://github.com/campersau/ungit/actions/runs/55682312
> GitHub Action to automatically bump dependencies and create pull request

- .github/workflows/ci.yml
- appveyor.yml
As mentionend in https://github.com/FredrikNoren/ungit/pull/1296#issuecomment-601048594 here is the github workflow for running tests on push and pull requests and uploading electron packages as artifacts.
This also removes the artifact publishing from appveyor because it is no longer needed and they had issues running on macos https://github.com/FredrikNoren/ungit/pull/1241#issuecomment-556998552.
I have run them for quite some time and the windows / macos builds are a bit flaky.
On windows the tests sometimes fail in [`Auto checkout on branch creation.`](https://github.com/campersau/ungit/runs/521314055?check_suite_focus=true#step:19:343)
On macos it sometings [hangs during packaging](https://github.com/campersau/ungit/runs/521357509?check_suite_focus=true).
> Add GitHub Action for CI

- source/git-promise.js
Follow up to https://github.com/FredrikNoren/ungit/pull/1305 after [I have asked on the git mailing list](http://public-inbox.org/git/CAJTX9qQUDr6qywMjN0=2OL7AFdbkwGRB1zpKj_fi2_=LEdVGBg@mail.gmail.com/T/). The recommendation there was to set the `GIT_EDITOR=:` environment variable but the `core.editor=:` config option also works to prevent opening the git editor in general.
Fixes https://github.com/FredrikNoren/ungit/issues/1301
> Set git core.editor=: to prevent opening git editor

- CHANGELOG.md
- package-lock.json
- package.json
- Continue rebase fails with git 2.26 [#1301](https://github.com/FredrikNoren/ungit/issues/1301)
- Dependency updates [#1304](https://github.com/FredrikNoren/ungit/pull/1304), [#1300](https://github.com/FredrikNoren/ungit/pull/1300), [#1297](https://github.com/FredrikNoren/ungit/pull/1297), [#1295](https://github.com/FredrikNoren/ungit/pull/1295)
- ignore nmclicktests and ci files in npm package [#1306](https://github.com/FredrikNoren/ungit/pull/1306)
- GitHub Action CI [#1298](https://github.com/FredrikNoren/ungit/pull/1298)
- GitHub Action dependency bump [#1296](https://github.com/FredrikNoren/ungit/pull/1296)
> Prepare version 1.5.6

- Gruntfile.js
[`pkg-versions` uses `Object.keys`](https://github.com/sindresorhus/pkg-versions/blob/d548b95001574add793f5059be74c41c0942a608/index.js#L6) which does not return the keys in order (at least for big objects).
> fix bumpdependencies by not relying on Object.keys order

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- public/source/main.js
- source/git-api.js
Use the node-watch drop-in replacement to provide recursive watching on Linux
Fixes #1164
> Node watch

- CHANGELOG.md
- components/branches/branches.html
- components/commit/commit.html
- components/dialogs/dialogs.js
- components/dialogs/formDialog.html
- components/dialogs/prompt.html
- components/graph/graph.html
- components/header/header.html
- components/login/login.html
- components/path/path.html
- components/remotes/remotes.html
- components/staging/staging.html
- components/submodules/submodules.html
- nmclicktests/spec.authentication.js
- nmclicktests/spec.discard.js
- nmclicktests/spec.remotes.js
- nmclicktests/spec.submodules.js
- public/index.html
* Adding alt text to logo and gravatar
* Adding (invisible) labels to dropdown buttons
* Adding `lang="en"` to `<html>`
* Adding aria-labels for `input`s without label
* Removing placeholders when they are identical to label
* Adding `tabindex` to dialog to properly add tabbing behavior
* Use bootstrap alert to display login errors
The remaining big accessibility thing would be contrast between font-color and background, but that would introduce very visible changes.
> Fixing some accessibility issues

- .github/workflows/ci.yml
- .travis.yml
node 14 (the current latest version) breaks clicktests on linux, not sure why exactly yet.
Examples:
https://travis-ci.org/github/FredrikNoren/ungit/builds/679684386
https://github.com/FredrikNoren/ungit/runs/619568794
> use node 10 for publishing artifacts and releasing packages

- components/branches/branches.html
- components/branches/branches.less
- components/remotes/remotes.html
- components/submodules/submodules.html
- nmclicktests/spec.remotes.js
- public/less/styles.less
* Use only `<li` in dropdown lists
* Use bootstrap divider consistently
* Add margin for action buttons
* Only show scrollbar when necessary
---
*Before (submodules)*
*After (submodules)*
---
*Before (branches)*
*After (branches)*
> Format dropdown menus

- components/graph/git-node.js
- components/graph/graph.html
Fix what @jung-kim intended to fix in #1311, but got lost in the whitespace-refactor:
Only show search button if there are hidden refs.
It was included in the first commit of that PR, but subsequently lost:
https://github.com/FredrikNoren/ungit/blob/80fb354caba0c9d316a4a7960994afc10dad6ad9/components/graph/graph.html#L44
---
Also fixes an issue with the selection of tags and branches to display:
For `numRefsToShow` = 5, `numBranchesToShow` = 3, and `numTagsToShow` = 2,
only enforce the branch and tag numbers if the total number of refs exceeds the limit.
Examples: 
- 3 branches and 2 tags -> 3 branches and 2 tags
- 5 branches and 1 tag -> 4 branches and 1 tag
- 5 branches and 2 tags -> 3 branches and 2 tags
- 2 branches and 5 tags -> 2 branches and 3 tags
(Previously, the tag limit would …
> Fix ref-search button display

- components/branches/branches.less
- components/graph/git-node.js
- components/graph/git-ref.js
- components/graph/graph.less
- public/less/styles.less
- public/source/main.js
This PR contains three separate, but related changes.
The screenshots build on top of each other, but the commits are independent.
- Style autocomplete like dropdowns
- Align autocomplete ref icons with dropdown ref icons
- Fixed width for dropdown/autocomplete icons,
so that the branch and tag names are aligned
> Style autocompletes like dropdowns

- components/commit/commit.js
- source/git-parser.js
- test/spec.git-api.conflict.js
- test/spec.git-parser.js
Flatten total-lines-changed object to allow the commit object to not error when passed an empty object.
> Fix for commit component with empty args object

- CHANGELOG.md
- components/graph/graph.js
- components/staging/staging.js
- public/source/main.js
**Before**
Base on @campersau comment here : https://github.com/FredrikNoren/ungit/pull/1340#issuecomment-622092861
Tooltip are not loaded until a repo is opened
**Fix**
Instead of relying on some hand made event to init tooltips, this PR uses the event-delegation method provided by bootstrap tooltip (based on jquery.on) to init tooltips on existing elements and new elements.
https://getbootstrap.com/docs/4.0/components/tooltips/
> Fix: init tooltips from the app start

- Gruntfile.js
- package-lock.json
- package.json
Even though the `color` package is required and exposed during browserify, I could not find any usage of it.
> Remove unused color dependency

- components/commit/commit.html
- components/commitdiff/commitdiff.html
- components/header/header.html
- components/refreshbutton/refreshbutton.html
- components/staging/staging.html
- components/stash/stash.html
- package-lock.json
- package.json
- public/less/generic.less
- public/less/styles.less
- public/less/variables.less
- public/source/jquery-ui.js
- public/source/main.js
This PR has two changes that are not easily possible to split.
Currently, ungit is (unintentionally probably) using the jQuery UI tooltips instead of the bootstrap ones.
1. Only import the jQuery UI widgets that are used, i.e. `autocomplete`
- Switch from `jquery-ui-bundle` to `jquery-ui` package
- Add a new file that managest the jQuery UI import
- ~Remove jQuery UI styles import as we use our own (see #1327)~
- Replace jQuery UI styles import with only core styles, thanks for the hint @ylecuyer 
2. Add custom styling to bootstrap tooltips
3. Fix placement of tooltips in button groups
---
> Reduce jQuery UI imports and use Bootstrap tooltips

- Gruntfile.js
- package-lock.json
- package.json
The grunt task to embed images was added in 6e5877361bc3b88074b4d9cfe98f979505cf1ed4 when ungit had a lot more images (which were referenced from CSS). 
Now, the task only embeds the fonts used by ungit, which is actually counter-productive:
1. The font declaration includes the `local()`-function so that fonts don't need to be loaded if they are already installed, but this optimization is redundant as the font is embedded in the same file.
https://github.com/FredrikNoren/ungit/blob/09232a774f8d53b3e28db68453d93fdadaa20429/public/less/generic.less#L12-L24
2. Bootstrap includes multiple file types of the glyphicon font so the browser can pick their best supported one. By embedding the fonts, all alternatives are served.
https://github.com/FredrikNoren/ungit/blob/09232a774f8d53b3e28db68453d93 …
> Remove image embed

- package.json
This was added a long time ago  when node-webkit was used instead of electron. https://github.com/FredrikNoren/ungit/commit/68cd534c0e8a60125fbd513660485e3c41f614b5
> remove window information from package.json

- CHANGELOG.md
- package-lock.json
- package.json
- Init tooltips from the app start [#1343](https://github.com/FredrikNoren/ungit/pull/1343)
- Fixing some accessibility issues [#1318](https://github.com/FredrikNoren/ungit/pull/1318)
- Flatten total-lines-changed object [#1330](https://github.com/FredrikNoren/ungit/pull/1330)
- Set electron window icon explicitly so it works during debug and on linux [#1347](https://github.com/FredrikNoren/ungit/pull/1347)
- Only display ref search button when there are hidden refs [#1311](https://github.com/FredrikNoren/ungit/pull/1311), [#1325](https://github.com/FredrikNoren/ungit/pull/1325)
- Cleanup CSS styles [#1339](https://github.com/FredrikNoren/ungit/pull/1339), [#1328](https://github.com/FredrikNoren/ungit/pull/1328), [#1331](https://github.com/FredrikNoren/ungit/pull/1331), …
> Prepare version 1.5.7

- Gruntfile.js
- components/graph/git-node.js
- Only expose dependencies used by the components
- skip parsing of large libraries without dependencies
> Clean up browserify

- CHANGELOG.md
- source/git-promise.js
While trying to migrate from grunt to script files, I noticed that the mocha unittest weren't existing right away. I tracked the problem down with [`wtfnode`](https://github.com/myndzi/wtfnode) to our git-promise timeout (introduced in https://github.com/FredrikNoren/ungit/pull/1192) which wasn't cancelled if the git call was successful and didn't timed out.
> Clear git-promise timeout when git command was successful

- components/commit/commit.less
- components/commitdiff/commitdiff.less
- components/graph/graph.less
- components/header/header.less
- components/home/home.less
- components/staging/staging.less
- components/stash/stash.less
- public/less/d2h.less
- public/less/styles.less
While prettier does some formatting of less files (double to single quotes, lowercase hex colors), it doesn't do others. 
Formatting in this PR that is not done by prettier:
- Empty line before rule
- Remove units for zero values (`0px` → `0`)
- Use long form for color declarations (`#ff5` → `#ffff55`)
(This makes it easier to later regex all colors.)
- Remove empty rules
> Format less files

- test/spec.credentials-helper.js
> The credentials-helper tests sometimes don't pass when I am having a crashed ungit instance opened in chrome because I stopped the server and the crashed ungit pages tries to reconnect by sending polling requests with socket.io which then the node server in the credentials-helper test picks up and throws inside of the request handler which means that the server does not a response and eventually times out. So to prevent this edge case we could add a timeout to the node response so it times out faster.
See https://github.com/FredrikNoren/ungit/pull/1365#issuecomment-629758116y
> prevent tests hangs in credentials-helper

- source/server.js
I made a mistake in https://github.com/FredrikNoren/ungit/pull/1350 which prevented ungit from beeing loaded in electron. I assumend that `fs.readdir(..., { withFileTypes: true })` would just work in electron but since we are using asar it apparently does not. See https://github.com/electron/electron/issues/19074
First commit refactors the code to the `fs.readdir` and `fs.stat` equivalent.
The second commit gets rid of the directory check completely because we already catch and ignore all errors 😄
> Fix plugin loading in electron

- .mochaclicktest.json
- .mochatest.json
> There are some CI cancellations now because of tests hangs: 
> - https://github.com/FredrikNoren/ungit/runs/685921173?check_suite_focus=true
> - https://ci.appveyor.com/project/FredrikNoren/ungit/builds/32943552/job/m2anlaiuae4owaw8
> 
> So we might need to add [`--exit`](https://mochajs.org/#-exit) for now because I haven't reproduced these hangs yet.
https://github.com/FredrikNoren/ungit/pull/1365#issuecomment-630683583
> force mocha tests to exit to avoid hangs

- components/branches/branches.js
- components/remotes/remotes.js
- source/config.js
- source/git-api.js
closes #1380
Note the discardchanges test does fail with this due to:
` Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (ungit\test\spec.git-api.discardchanges.js)`
however I didn't see the specific reason is failing and it fails in master on my machine so ignored that.
An alternative would be to add an offline option (with a config setting to default start in this) that takes a step further to not hit remote repos and allow local work.
Review and let me know whats best.
> When autoFetch=false don't make remote repo calls automatically

- CHANGELOG.md
- components/staging/staging.html
- components/staging/staging.less
> Resizing horizontally (typically by accident when trying to resize vertically only, in my case) screws up the staging panel layout.  This change prevents that.
This is an adequate solution (to my mind at least) to #315, which has been bothering me too.
~If the change is acceptable, would you like me to bump the patch version and update CHANGELOG.md?  The instructions at [CONTRIBUTING.md](https://github.com/FredrikNoren/ungit/blob/master/CONTRIBUTING.md#pull-requests) seem to be out-of-date w/r/t the current CHANGELOG.md style.  Perhaps just include a line under "Fixed" in the "Unreleased" section?~
Note: the Windows test which is failing below with a 404 fetching resources is currently passing on my fork.
> Prevent commit message <textarea> from resizing horizontally

- CHANGELOG.md
- package-lock.json
- package.json
- Clear git-promise timeout when git command was successful [#1357](https://github.com/FredrikNoren/ungit/pull/1357)
- When autoFetch=false don't make remote repo calls automatically [#1381](https://github.com/FredrikNoren/ungit/pull/1381)
- Prevent commit message <textarea> from resizing horizontally [#1390](https://github.com/FredrikNoren/ungit/pull/1390)
- Diff out is not properly escaping [#1387](https://github.com/FredrikNoren/ungit/issues/1387)
- Migrate clicktests from nightmare to puppeteer [#1336](https://github.com/FredrikNoren/ungit/pull/1336)
- Prettify code with prettier [#1316](https://github.com/FredrikNoren/ungit/pull/1316)
- Switch from JSHint to ESLint [#1360](https://github.com/FredrikNoren/ungit/pull/1360)
- Bump Dependencies …
> Prepare version 1.5.8

- .gitignore
- public/css/.gitignore
- public/js/.gitignore
- scripts/build.js
Version 1.5.8 has the `public/js/ungit.js` and `public/css/style.css` files missing on npm.
It seems that all `.gitignore` files get transformed to `.npmignore` (unless there is an actual `.npmignore` file), even when they are in subfolders. 
This PR removes the `.gitignore` files that are not in the root folder and creates the required folders in the build step.
> Fix git ignore settings

- .gitignore
- package-lock.json
- package.json
- scripts/build.js
Generate source maps for less and extract both less and browserify source maps to separate `.map` files.
This also reduces the size of the `ungit.js` bundle from 4.55mb to 1.76mb.
> Generate and extract source maps

- package.json
Since #1395 boostrap is now a npm dependency, but we don't want to automatically upgrade it.
> ignore upgrading bootstrap automatically

- .github/workflows/bump.yml
It is now possible to trigger workflows manually: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
> run bump dependency workflow manually

- clicktests/spec.generic.js
merging now automatically appends the target branch name to the commit message
Before git 2.28:
```
Revert "Merge branch 'testbranch'"
```
After git 2.28:
```
Revert "Merge branch 'testbranch' into master"
```
> fix tests for git 2.28

- LICENSE.md
- scripts/electronpackage.js
https://electron.github.io/electron-packager/master/interfaces/electronpackager.options.html#appcopyright
fixes https://github.com/FredrikNoren/ungit/issues/1411
> add copyright to electron executable

- CHANGELOG.md
- package-lock.json
- package.json
- Add copyright to electron executable [#1411](https://github.com/FredrikNoren/ungit/issues/1411)
- Generate and extract source maps [#1394](https://github.com/FredrikNoren/ungit/pull/1394)
- Import Bootstrap from npm and upgrade to latest 3.x [#1395](https://github.com/FredrikNoren/ungit/pull/1395)
- Bump Dependencies upgrading from electron 9.x to 10.x [#1392](https://github.com/FredrikNoren/ungit/pull/1392), [#1406](https://github.com/FredrikNoren/ungit/pull/1406)
> Prepare version 1.5.10

- CHANGELOG.md
- clicktests/environment.js
- clicktests/spec.generic.js
- components/graph/graph.html
fixes https://github.com/FredrikNoren/ungit/issues/190 (no commit checkout)
> checkout with double click

- CHANGELOG.md
- package-lock.json
- package.json
- Doubleclick to checkout [#190](https://github.com/FredrikNoren/ungit/issues/190)
- Use page.waitForTimeout API in tests [#1422](https://github.com/FredrikNoren/ungit/pull/1422)
- Bump Dependencies [#1417](https://github.com/FredrikNoren/ungit/pull/1417), [#1423](https://github.com/FredrikNoren/ungit/pull/1423)
> Prepare version 1.5.11

- .github/workflows/ci.yml
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Use GITHUB_ENV for setting environment variables

- .github/workflows/ci.yml
by default the artifacts are kept for 90 days but for PRs we don't need to keep them for so long.
Also we can just re-run the workflow. This could also be changed in the GitHub repository settings, but I don't have permissions to do that.
https://github.blog/changelog/2020-10-08-github-actions-ability-to-change-retention-days-for-artifacts-and-logs/
> Add retention-days: 7 to uploaded artifacts

- CHANGELOG.md
- source/git-promise.js
I have done one [CI run](https://github.com/campersau/ungit/runs/1285422580?check_suite_focus=true) (only windows had the new git 2.29 version when I tested it) with [`--object-format=sha256`](https://github.com/campersau/ungit/commit/a8bdb97c20aedbb2c0dc8118b7192d0dc76297d7) and it looks like this is the only place which failed.
More information about git 2.29 https://github.blog/2020-10-19-git-2-29-released/
> Support git 2.29 sha256

- .travis.yml
- CHANGELOG.md
- package-lock.json
- package.json
- branches - can't re-enable disabled groups [#1434](https://github.com/FredrikNoren/ungit/issues/1434)
- Support git 2.29 sha256 [#1436](https://github.com/FredrikNoren/ungit/pull/1436)
- Bump Dependencies [#1427](https://github.com/FredrikNoren/ungit/pull/1427)
> Prepare version 1.5.12

- .github/workflows/ci.yml
- .travis.yml
- appveyor.yml
Run tests also on node 14 (lts) as node 15 is (will be) the new latest version.
[Travis already has node 15](https://travis-ci.org/github/FredrikNoren/ungit/jobs/739090853#L867), Appveyor and GitHub need more time.
> CI add node 14

- CHANGELOG.md
- source/git-api.js
Since node 14 passing `recursive` on linux will throw an exception.
https://nodejs.org/docs/latest/api/fs.html#fs_caveats
https://github.com/nodejs/node/commit/67e067eb06
Fixes https://github.com/FredrikNoren/ungit/issues/1389
cc @jung-kim
> Only watch recursive on mac and windows

- CHANGELOG.md
- package-lock.json
- package.json
- Update socket.io to version 3.0.0 [#1443](https://github.com/FredrikNoren/ungit/pull/1443)
- Bump Dependencies [#1442](https://github.com/FredrikNoren/ungit/pull/1442), [#1444](https://github.com/FredrikNoren/ungit/pull/1444), [#1448](https://github.com/FredrikNoren/ungit/pull/1448), [#1449](https://github.com/FredrikNoren/ungit/pull/1449)
Since electron got bumped to 11.x.x we now also support darwin-arm64 electron builds.
> Prepare version 1.5.14

- bin/ungit
- clicktests/environment.js
- clicktests/spec.remotes.js
- clicktests/spec.screens.js
- components/header/header.js
- components/home/home.js
- components/imagediff/imagediff.js
- components/path/path.js
- components/repository/repository.js
- public/main.js
- public/source/main.js
- source/address-parser.js
It's fine for query parameters to have visible `/` in them, and it makes it easier to work with the ungit URLs
> Encode URI paths with slashes

- .github/workflows/ci.yml
- CHANGELOG.md
- package-lock.json
- package.json
- Add clipboard button on commit [#1462](https://github.com/FredrikNoren/ungit/pull/1462)
- Encode URI paths with slashes [#1378](https://github.com/FredrikNoren/ungit/pull/1378)
- Bump Dependencies [#1456](https://github.com/FredrikNoren/ungit/pull/1456), [#1464](https://github.com/FredrikNoren/ungit/pull/1464)
- Bump elliptic from 6.5.3 to 6.5.4 [#1468](https://github.com/FredrikNoren/ungit/pull/1468)
- Bump y18n from 4.0.0 to 4.0.1 [#1471](https://github.com/FredrikNoren/ungit/pull/1471)
- git 2.3x changes break unittests [#1472](https://github.com/FredrikNoren/ungit/issue/1472)
Also explicit set `node-version` to `15` for GitHub Workflow
> Prepare version 1.5.16

- source/git-parser.js
- test/spec.git-parser.js
We use the `-z` flag within git log to separate commits with NULL chars instead of new lines
In this case for example there is no one but two NULL chars before the next commits thus failing with the previous code
> Fix: More than one NULL to separate commits. #1460

- components/repository/repository.html
- components/textdiff/textdiff.js
- source/config.js
This PR will allow the user to specify `tab-size` for the diff view.
Using tabs looks awful without this configuration (specially in `side-by-side` view) as it cause the text to be over indented as the default `tab-size` value is 8. 
Before (Tab size default to 8):
After (Tab size set to 2):
> Add Tab Size Configuration

- .prettierrc
- package-lock.json
- package.json
- public/source/bootstrap.js
- public/source/jquery-ui.js
- source/git-promise.js
- source/utils/cache.js
- test/spec.cache.js
- tsconfig.json
this adds some non-commital TypeScript support, by adding JSDoc comment parsing to Prettier (allows checking for mistakes) and enabling error highlighting in VS Code and any others that might run TypeScript checking.
Note that no compiling is needed, this just adds static configuration to help out VSCode.
> Types: add support for VSCode IntelliSense

- source/git-api.js
source: snyk.io
--- 
It's possible to get remote code execution via argument injection.
The issue occurs when calling the /api/fetch endpoint. The user input is passed to the git subcommand fetch. Even if a safe API like spawn is used to execute shell commands (https://github.com/FredrikNoren/ungit/blob/6aff6dccc4f15a66f22fd44415d57c8e32eebf39/source/git-promise.js#L69), in this specific case it's still possible to run arbitrary commands via argument injection.
The fetch subcommand accepts a special argument --upload-pack (https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---upload-packltupload-packgt). Since the user controls two values provided to the fetch git subcommand (remote and ref), it is possible to execute arbitrary commands by providing the remote value to be …
> Fix potential remote code exec

- components/staging/staging.less
- components/textdiff/textdiff.js
The closing tag isn't needed as it isn't replaced.
Ignore unchanged lines which start with `-` or `+`.
> fix patch checkbox html

- bin/ungit
Changes `child_process.spawn` to `child_process.fork` to create new node process to run `server.js`.
Currently `bin/ungit` creates a new child process using `spawn` with the first argument of `process`, which is expected to be `"node"` or in some OS (apparently) `"nodejs"`. When running this script from other programs, for example as part of a [VSCode extension](https://github.com/Hirse/vscode-ungit), this expectation does not hold and the first argument is actually `"Code.exe"`. Trying to spawn the ungit server there fails for obvious reasons.
Since the goal is to create a new node process (with the same one that is already running), we can shorthand it by using [`fork`](https://nodejs.org/api/child_process.html#child_processforkmodulepath-args-options):
> The child_process.fork() method …
> Use fork to spawn a new node process

- source/config.js
- source/server.js
Return exit-code 1 instead of 0 when passing to ungit wrong arguments
Fixes #1548
> Fix exit code on wrong config

- bin/ungit
This makes sure the child process `server.js` is killed when the parent `ungit` gets killed
Fixes #1552
> Kill server when ungit gets killed

- components/commit/commit.less
| Before | After |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/d9724e3f-c139-4178-8bb5-7e631ca49a93) | ![image](https://github.com/user-attachments/assets/93716bd1-1c26-46bb-b48a-5766c7cc907c) |
> Use monospace font-family in commit body

- package-lock.json
- package.json
- source/git-api.js
Lately I started to work on a node project with a lot of dependencies, when opening this project in ungit I started to get this error:
```
2024-08-18T18:21:39.758Z - error: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/ylecuyer/Projects/project/.git/index.lock'
```
So far I was able to get ungit running by changing the limit of inotify nodes doing
```
sudo sysctl fs.inotify.max_user_watches=524288 && sudo sysctl -p
```
And when checking the number of used inotify nodes, It is really big (263k):
```
ylecuyer@inwin:~/Projects/inotify-info$ ./_release/inotify-info 
------------------------------------------------------------------------------
INotify Limits:
max_queued_events    16,384
max_user_instances   128
max_user_watches     524,288 …
```
> Better: change watcher to properly filter ignored directories
