FredrikNoren/ungit

components/staging/staging.html
components/staging/staging.js

Commit on enter or alt enter fix: #509

---

clicktests/test.submodules.js
components/submodules/submodules.html
components/submodules/submodules.js
components/submodules/submodules.less
package.json
source/git-api.js

I was working on #513 and got side tracked and did it for submodule first....
Will do same thing for remotes in similar fashion.

Delete submodule via UI

---

components/staging/staging.less

fix long file path name: fix #317

---

clicktests/test.generic.js
components/staging/staging.js

Put confirm box to discard changes button fix #524

---

package.json

Downgrade forever-monitor

---

Gruntfile.js
package.json

Fix build on Windows (browserify)

---

public/source/main.js

Now it's really easy to browse folders, just push right arrow to browse into selected folder in autocomplete list.

Easy Browsing

---

source/git-api.js

Baserepopath handle win root dir. Fixes #537

---

public/source/main.js
source/config.js

Passing `path.sep` as a config field.

easy browsing for windows fix: 543

---

components/staging/staging.html
components/staging/staging.js
source/git-parser.js
test/spec.git-api.branching.js
test/spec.git-api.conflict.js
test/spec.git-api.js
test/spec.git-api.submodule.js

fix commit with renames

---

clicktests/test.screens.js
public/source/main.js
public/source/navigation.js

use encodeURIComponent which also encodes ampersands
fixes #567

fix location hash path

---

components/commitdiff/commitdiff.js

textDiffType was missing from args
fixes #571

fix loading more commit changes

---

source/git-api.js

this greatly improves performance if multiple files get changed simultaneously. Because on each `working-tree-change` event the stash and other components would reload their state.
~~Maybe related to #569~~

debounce working tree changes

---

source/git-api.js

Removes notes from commit graph

---

package.json
source/config.js
source/server.js

Using [os-homedir](https://github.com/sindresorhus/os-homedir)

Using os-homedir

---

clicktests/test.submodules.js
public/less/d2h.less

~~Making submodule test more resilient via using ungit as submodule instead of temp git directory.~~
It also has a diff2html css fix for hiding y overflow bar as well.

hiding y overflow bar for diff2html

---

components/commitdiff/commitdiff.html
components/commitdiff/commitdiff.js

All of these are now being done by share code within textdiff

Removing unnecessary functions from commit diff

---

clicktests/helpers.js
clicktests/test.generic.js
components/staging/staging.html
components/staging/staging.js
components/staging/staging.less
source/git-parser.js
source/git.js
test/spec.git-api.branching.js
test/spec.git-api.conflict.js
test/spec.git-api.js
test/spec.git-api.submodule.js

show additions and deletions in staging area

---

clicktests/test.all.js
clicktests/test.branches.js
clicktests/test.noheader.js
components/branches/branches.html
components/branches/branches.js
components/branches/ungit-plugin.json
components/graph/git-node.js
components/graph/graph.less
components/graph/ref.js
components/remotes/remotes.html
components/remotes/remotes.js
components/repository/repository.html
components/repository/repository.js
components/repository/repository.less
components/submodules/submodules.html
public/less/styles.less

Added branch list, this is same as #459.
* ~~Display text is "@<<current branch>>".  I'm not sure if this is a good idea but simply displaying branch name wasn't indicative enough.~~ having branch icon in the box should be indicative enough
* Branch list sorted

Added branch list fix: #459

---

components/graph/graph.html
components/stash/stash.html

Add more tooltips

---

.travis.yml
source/git-api.js

Fix orphan branch error since git 2.5.2

Fix orphan branch error since git 2.5.2

---

components/header/header.less

Make the color of version number string easier to read

Make the color of version number string easier to read

---

.travis.yml
source/git-parser.js

git 2.6.0 does not allow hunk with no change
Fix test failures.

git 2.6.0 does not allow hunk with no change

---

clicktests/environment.js
clicktests/test.discard.js
clicktests/test.generic.js
clicktests/ui-interactions.js

Doing proper shutdown/clean up for tests.

Expand scope of removing message listeners during shutdown

---

source/git-api.js

Change commit ordering to date-order.

---

.travis.yml

Travis-CI: Move to nodejs 4.1

---

components/graph/graph.less

Toning down checked out branch accent

---

source/git-api.js
source/git.js

Thought sent this in but I guess I haven't.
fixes #657
Didn't know how easy it was to stream data using pipe but I will be replacing back end to use streams where it can when I do conversions for promises.

Fix image diff issue #657

---

.travis.yml
appveyor.yml
clicktests/testsuite.js

Add appveyor

---

appveyor.yml
clicktests/helpers.js
clicktests/test.authentication.js
clicktests/test.branches.js
clicktests/test.discard.js
clicktests/test.generic.js
clicktests/test.noheader.js
clicktests/test.plugins.js
clicktests/test.remotes.js
clicktests/test.screens.js
clicktests/test.submodules.js
clicktests/testsuite.js
clicktests/ui-interactions.js
test/spec.git-api.submodule.js

Various fixes to get them more stable

Improve clicktests #663

---

.travis.yml

Seems like build has been passing even with npm install step in travis was having [many warnings and some errors](https://travis-ci.org/FredrikNoren/ungit/jobs/101333367)...
https://github.com/travis-ci/travis-ci/issues/4771

define g++ spec for npm warnings.

---

components/staging/staging.js

Add staging msg reset for merge and rebase

---

CHANGELOG.md
CONTRIBUTING.md
README.md

Introduce changelog

---

CHANGELOG.md
components/graph/graph.less
components/repository/repository.less

Removing hover effect
fix: #688

Removing hover effect

---

CHANGELOG.md
components/graph/git-ref.js

fix remote tag duplicate problem

---

CHANGELOG.md
bin/ungit

Fix git hooks failing on non-ascii files

---

CHANGELOG.md
Gruntfile.js
components/app/app.js
public/index.html
public/source/server.js

related: #679 
upgrade keen.io client code.

Keen client code upgrade

---

CHANGELOG.md

Add change log.
I keep forgetting cause I'm an imbecile....

add change log for rebase message

---

CHANGELOG.md
clicktests/test.all.js
clicktests/test.bare.js
components/path/path.html
components/path/path.js
components/repository/repository.js
components/staging/staging.js
components/stash/stash.js
source/git-api.js
source/git-promise.js

Fix barerepo

---

CHANGELOG.md
source/git-promise.js
test/common.js
test/spec.git-api.diff.js

by checking if the repository is bare and if so not call `git.status`
closes #728

fix diffs for bare repositories

---

source/git-promise.js

To fix broken windows path problem created by #739

return normalized path for windows

---

package.json
source/sysinfo.js

fix #746 
(probably will not be nice to old npm and node versions)

remove deprecated npmconf

---

clicktests/environment.js

Fix the issue where autocheckout option in .ungitrc breaking the tests

Fix autocheckout breaking tests

---

source/git-promise.js

I think this fixes git 2.9.0 bug

Add no renames flag

---

CHANGELOG.md
clicktests/test.stash.js
components/commit/commit.html
components/commit/commit.js
components/commitdiff/commitdiff.html
components/commitdiff/commitdiff.js
components/staging/staging.html
components/staging/staging.js
components/stash/stash.html
components/stash/stash.js
source/git-api.js
source/git-parser.js
test/spec.git-api.stash.js

reference #444
Clicking on the stash title will show the changed files.

show diffs for stash items

---

source/bugtracker.js
source/config.js
source/server.js
source/sysinfo.js
source/usage-statistics.js

fully promisifying sysinfo.js 
~~[work still under progress...]~~
ready for review

sysinfo.js refactor

---

components/stash/stash.html

Adding quick tooltip
cc: @campersau

Adding tooltips

---

CHANGELOG.md
components/home/home.js
components/imagediff/imagediff.js

As reported on May 11th by @sebastianmay for rootPath feature issue #609 I just recently hit that one as well and I hope this will get pulled to the next version. Thanks and Cheers!
:beers:

Fix for favorites linking in case of rootPath option is used

---

components/graph/edge.js
components/graph/git-node.js
components/graph/graph.js

As some of you might have noticed, git graph edge calculation often goes hay wire in certain edge cases and this is to simplify the logic and fix that issue

Improved git graph edge calculation

---

clicktests/test.loadAhead.js
source/git-api.js

I would have to kick Travis CI several times to prove my theory but my current suspicion is that these events fired too quickly following the api call and causing troubles in client side and serverside.
related: #787, #762

Add debounce 

---

source/git-promise.js

fix: #796
I guess windows throws "permission denied" when unable attain file lock.  Which is possible in ungit as high degree of parallelization of git operations we do in the background.
Hopefully this will fix windows test failures.

Add retry for windows file permission issue exception

---

appveyor.yml

`appveyor/branch` and `appveyor/pr` test are duplicate, running only one out of two

Skip pr test

---

CHANGELOG.md
public/source/main.js

Added search by git container folder name

---

public/source/main.js

fixes #810 
No changelog entry because the bug was not released.
See second commit for the fix.

fix repository search

---

CHANGELOG.md
Gruntfile.js

readd imagemin grunt task

---

CHANGELOG.md
source/git-promise.js

add null check for stash result

---

CHANGELOG.md
clicktests/environment.js
clicktests/test.branches.js
clicktests/test.commands.js
components/graph/git-node.js
components/graph/graph.js
package.json
source/git-api.js

cc: @Ajedi32 @brettswift
This will fix the git checkout and I think that was the main concern of the issue #283.  Is there any other operations I should consider?

Git command line exec to be applied to ungit

---

CHANGELOG.md
components/graph/graph.js

Fix initial page load when loaded node does not fits in screen.

---

README.md

filewatch readme update

---

source/git-api.js

check if filename is null

---

source/git-api.js

This was one of the nasties bug ever...  Apparently `fs.watch` hangs indefinitely when folder doesn't exist.  
in unix, we watch `.git/refs/heads`, `.git/refs/remotes`, and `.git/refs/tags`.  And git sometimes does not create folders if there are not necessary.  for examples, in recent Travis failures, `.git/refs/remotes` was not created as there are not remotes in test git repo and result in an event loop to be stuck.  
This would have caused memory leak and slew of other problems and this is a quite nasty one...
I really wish they would move entire standard node libs to promises...

Skip fs watch if folder is missing

---

README.md

Added screenshot showing the integration of Ungit with Codiad web-based text editor.
Screenshot uses image linked to issue #839

Link to Codiad plugin for Ungit

---

README.md

see #845 
npm version is taken from https://nodejs.org/en/blog/release/v4.1.0/

Update node and npm versions in readme

---

CHANGELOG.md
components/commitdiff/commitdiff.html
components/staging/staging.html
package.json

Fix spelling mistakes

---

CHANGELOG.md
components/staging/staging.js
package.json

Compute the allStageFlag of the staging component by comparing the total and selected staging files.
Improves the behavior of the `Toggle all` button:
When all files are selected it will unselect all files.
If one or more files are unselected it will select all files.
This is my first time using knockout.js so if there are better ways of doing things, please point them out!
resolves #859

Update "Toggle all" button after commit or changing selected files

---

CHANGELOG.md
public/source/main.js
source/server.js

fix: #861
I will add missing test for this later...

Fix path auto complete

---

components/commitdiff/commitlinediff.js
components/imagediff/imagediff.js
components/staging/staging.js
components/textdiff/textdiff.js
public/source/server.js

* fix diff flickering issue
* optimized text and image diff generation via smart caching
* recycle diff objects for memory optimization and state maintenance
* `invalidateDiff` function now invalidates only, does not render, which has been confusing me for very long time...  >.<

Diff optimization and fix flickering issue

---

CHANGELOG.md
components/graph/graph.js
package.json

Fix HEAD branch order when redraw

---

CHANGELOG.md
package.json
source/server.js
source/ungit-plugin.js
source/usage-statistics.js
source/utils/cache.js
test/spec.cache.js

One of the last component to promisify within server side...
Frankly kind of went overboard with the new `cache.js` implementation and began adding more stuffs that we don't even need...  rawr...

Promisify cache.js

---

CHANGELOG.md
components/staging/staging.js
components/textdiff/textdiff.js
package.json

fix: #875
* fix load more button
* change behavior on commit so that pathced files will result in `none` edit state after commit

fix load more

---

CHANGELOG.md
package.json

Update diff2html min ver

---

package.json
source/config.js

Fix yargs config after updating it to version 7

---

CHANGELOG.md
package.json
source/config.js

Aspirin against your headache fixed #890

disable strict mode for startup params and config

---

CHANGELOG.md
clicktests/environment.js
clicktests/helpers.js
clicktests/test.commands.js
clicktests/test.stash.js
clicktests/testsuite.js

for clicktest stabilization
* click test log fix
* using `waitFor` instead of doing sleep and check

Using waitfor

---

CHANGELOG.md
source/git-api.js

Using normalized file path and refactoring file watch function

Filewatch refactor

---

CHANGELOG.md
Gruntfile.js

* remove async from `Gurntfile.js`
* Throttle parallel tests

remove async from grunt and throttle parallelization

---

CHANGELOG.md
components/app/app.js
package.json

Fix #912 
@campersau thanks for the catch, that was a silly mistake by me

Fix this context issue for gitSetUserConfig

---

CHANGELOG.md
components/graph/git-graph-actions.js
package.json

Turns out the previous fix crashes when the ref isn't in the viewport.

Don't rely no having a local ref available

---

CHANGELOG.md
components/stash/stash.js
package.json

I find it very irritating that you are not asked before deleting a stash ....
However I did not test this with auto-stashing since I never used this feature.
Also I only used yesno and not yesnomute since I am no JS expert and did not know there to store the mute timestamp.

Ask before deleting stash

---

CHANGELOG.md
components/home/home.js
package.json

Hide crentials in remote urls at home repo list

---

CHANGELOG.md
README.md
components/textdiff/textdiff.js
package.json

fixes #929 - Added a config setting to allow setting the default diff type

---

README.md

fix url for brackets-ungit screenshot

fix url for brackets-ungit screenshot

---

CHANGELOG.md
Gruntfile.js
components/commit/commit.js
nmclicktests/environment.js
public/index.html

Add parallel click test for speeding up dev efforts.
**Tests may time out depends on the parallelization level and resource allocation.** tried to minimize those variables via removing some of the unnecessary heavy network IOs but it is not gurantted.

Parallel click test

---

CHANGELOG.md
Gruntfile.js
components/graph/git-graph-actions.js
components/graph/git-node.js
components/graph/git-ref.js
components/graph/graph.less
components/graph/hover-actions.js
nmclicktests/spec.branches.js
package.json
source/git-api.js
test/spec.git-api.squash.js

fix: #129
tests and edge case considerations will follow but I will be traveling for about a month so I'm not sure when I can get this done...
Squashing from different branch
Backward Squashing from existing lineage

Squash multiple commits

---

CHANGELOG.md
components/app/app.html
components/app/app.js
package.json

So that people are aware of the new license. Discussion in #974

Show license notification on first start

---

CHANGELOG.md
components/app/app.html
components/app/app.js
nmclicktests/environment.js
package-lock.json
package.json
public/index.html

When the app launches for the first time the user gets redirected to https://faircode.io/product/Ungit/paywall?redirectUrl=http://localhost:8448 and from there it's a simple "Continue with Free" click to get back to the app, or "Continue with Commercial" to sign up for a subscription.

Switch to Faircode paywall, remove license popup

---

CHANGELOG.md
components/header/header.html
components/header/header.less
package.json

Small link in the UI so people can get to the Faircode page easily

Add plans and license link

---

CHANGELOG.md
LICENSE.md
README.md
components/header/header.html
package.json
public/index.html

Revert to MIT

---

CHANGELOG.md
bin/ungit
package.json

Completely forgot to push this...
Also, sneaking in fix for #999

fix the issue where browser opens before ungit start. fix #994

---

CHANGELOG.md
README.md
components/textdiff/textdiff.js
package.json

* fix: #969
* added patreon for JK.

Show dummy diff when there is no diff.

---

components/staging/staging.html
components/staging/staging.js
nmclicktests/environment.js
nmclicktests/spec.generic.js
source/git-api.js
source/git-promise.js

Allows empty commit from the staging view interface
fixes #1028

Empty commits

---

components/graph/git-ref.js

Remove heads from display name

---

CHANGELOG.md
components/branches/branches.js
package-lock.json
package.json

using the same logic as in the `git-ref` component
fixes #1031

fix branch dropdown delete action

---

bin/credentials-helper
components/app/app.js
components/dialogs/dialogs.js
public/source/server.js
source/git-api.js
test/spec.credentials-helper.js

WIP: Show remote in credential-helper popup

---

components/staging/staging.html
components/staging/staging.js
nmclicktests/spec.generic.js

Cancel button

---

components/repository/repository.js
components/staging/staging.html
components/staging/staging.js
nmclicktests/environment.js
nmclicktests/spec.remotes.js

Commit & push

---

Gruntfile.js

I got the following network error before:
@jung-kim how did it work for your in https://github.com/FredrikNoren/ungit/pull/1003 ?

copy nprogress.css to public/css/

---

CHANGELOG.md
components/graph/git-ref.js
components/staging/staging.html
components/staging/staging.js
nmclicktests/spec.remotes.js
package-lock.json
package.json

hide / disable push options if there is no remote

---

CHANGELOG.md
Gruntfile.js
components/branches/branches.html
components/branches/branches.js
components/gitErrors/gitErrors.html
components/gitErrors/gitErrors.js
components/graph/git-graph-actions.js
components/graph/git-node.js
components/graph/git-ref.js
components/graph/graph.js
components/remotes/remotes.js
nmclicktests/environment.js
nmclicktests/spec.helper.js
public/source/server.js
source/git-api.js
test/spec.helper.js

Fixes: #1014 
* Remote fetches functions will no longer spam git-error when offline 
* Added warning message when offline with offline message
* local git operations should be functional when off line

Handle offline mode more graciously

---

CHANGELOG.md
components/dialogs/dialogs.js
components/dialogs/formDialog.html
components/repository/repository.html
components/repository/repository.js
components/staging/staging.js
package-lock.json
package.json
public/source/server.js
source/git-api.js
test/common-es6.js
test/spec.git-api.js

fixes: #976 
Allow edit of top level .gitignore file via ungit, which allows ignore via folder

Allow edit of top level .gitignore file

---

bin/credentials-helper
source/git-api.js
test/spec.credentials-helper.js

fix for issue https://github.com/FredrikNoren/ungit/issues/1060

fixed issue #1060

---

CHANGELOG.md
bin/ungit
package-lock.json
package.json

Fix pathToNavigateTo not set when launchBrowser is false and launchCommand is set

---

components/graph/graph.js
components/staging/staging.html
components/staging/staging.js
nmclicktests/spec.generic.js
public/source/main.js
source/config.js
source/utils/cache.js

Misc. typos

---

CHANGELOG.md
components/dialogs/dialogs.js
package-lock.json
package.json

supersedes #1068 
Thanks @ylecuyer

Fix gitignore dialog width to 100%

---

CHANGELOG.md
components/dialogs/dialogs.js

Before
After
No version bump because it's minor

Fix: text-area width inside dialog

---

CONTRIBUTING.md

This started out as just adding `package-lock.json`  and ended up with me formatting and giving the document a quick grammar and spell check.

Reminder to bump package-lock.json.

---

CHANGELOG.md
components/remotes/remotes.js
package-lock.json
package.json

Treat remote fetch fail as an warning rather than error

---

CHANGELOG.md
Gruntfile.js
components/branches/branches.js
components/path/path.html
components/path/path.js
package-lock.json
package.json
public/index.html
public/source/main.js
source/git-api.js
test/spec.git-api.remote.js

add feature to do `--recurse-submodules` for git clone fix #1080

---

README.md

"unfriendlyness" -> "unfriendliness" 
Just a discovery when reading through the README file =)

Slight spell check update

---

source/git-promise.js

Generation of git errorCode to be case insensitive

---

CHANGELOG.md
components/app/app.js
package-lock.json
package.json
source/config.js

fixes: #1104 
(Needs more testing and verification on my part.)

allow pre-registration of repos

---

CHANGELOG.md
README.md
components/graph/edge.js
components/graph/git-node.js
components/graph/graph-graphics.html
package-lock.json
package.json
source/config.js
source/git-promise.js
source/server.js

- bind do `127.0.0.1` on default (ref #988)
- utilize `--no-optional-locks` (ref #1105)
- node highlight on path mouse hover (ref #1093)
- fix #1110

Force bind to '127.0.0.1' and add `--no-optional-locks` when applicable

---

CHANGELOG.md
bin/ungit
package-lock.json
package.json
source/config.js
source/server.js

Configurable binding ip

---

README.md

Updating references to VSCode Ungit

---

.travis.yml
CHANGELOG.md
components/crash/crash.js
public/source/main.js

Handle crashes with better logs

---

CHANGELOG.md
package-lock.json
package.json

@jung-kim Is this what you had in mind? If you don't want to release yet, you can just take the first commit.
For PR #1126

Update Changelog and version for localStorage wrapper

---

CHANGELOG.md
package-lock.json
package.json
public/source/server.js
source/config.js

- allow disabling of nprogress bar. fix [#1143](https://github.com/FredrikNoren/ungit/issues/1143)
- set `ungitVersionCheckOverride` as boolean in config. fix [#1102](https://github.com/FredrikNoren/ungit/issues/1102)

 allow disabling of nprogress bar

---

CHANGELOG.md
package-lock.json
package.json
source/git-parser.js

Better: Sort modules by name

---

components/commitdiff/commitdiff.html
components/graph/graph.html
components/graph/graph.js
components/header/header.html
components/refreshbutton/refreshbutton.html
components/staging/staging.html

* Fix existing tooltips not showing up
* Add tooltips to graph icons
* ![2018-10-25_17-47-26](https://user-images.githubusercontent.com/2564094/47538055-1e433500-d87e-11e8-9b44-cbbbb17724c0.png)
* ![2018-10-25_17-47-39](https://user-images.githubusercontent.com/2564094/47538058-2307e900-d87e-11e8-9a6d-ccda64bfbeab.png)

Fix and add more tooltips

---

package-lock.json
package.json
source/git-parser.js
test/spec.git-parser.js

Line coverage before:
```
----------------|----------|----------|----------|----------|-------------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------|----------|----------|----------|----------|-------------------|
All files       |    34.06 |    20.59 |     32.5 |    35.62 |                   |
src            |    33.33 |       21 |    33.33 |    34.88 |                   |
git-parser.js |    33.33 |       21 |    33.33 |    34.88 |... 58,360,361,363 |
src/utils      |       75 |        0 |        0 |       75 |                   |
file-type.js  |       75 |        0 |        0 |       75 |                 7 |
----------------|----------|----------|----------|----------|-------------------|
```
Line coverage now:
``` …
```

Better specs for git-parser + cleaning

---

.travis.yml

I removed EOL version of node and set to the latest available patch.

Remove EOL node from travis

---

CHANGELOG.md
components/textdiff/textdiff.js
package-lock.json
package.json
source/config.js

* Showing or Ignoring white space diff now configurable
> Default is `false`.
> User can configure otherwise in [configuration file](https://github.com/FredrikNoren/ungit#configuring)

"Ignore white space" in config

---

source/server.js

Sets the Content-Type to stop Firefox from issuing a warning.

Set Content-Type of /serverdata.js

---

components/commit/commit.less
components/commitdiff/commitdiff.html
components/staging/staging.html
components/staging/staging.less
components/stash/stash.less
components/textdiff/textdiff.js

Fixes #1229 
* Fix connected toggling 
* Use [Button Toolbar](https://getbootstrap.com/docs/3.3/components/#btn-groups-toolbar)
* Fix order of buttons
* Fix spacing of buttons
* Fix border radius of buttons in staging
* Unify text of buttons (and tooltips)
* Don't change text on toggle
* Use inactive as default for all buttons

More Consistent Diff Options

---

public/main.js

also show error message to user

fix electron portcheck to also include ungitBindIp as hostname

---

public/main.js

including link to github repository
Copied some of the standard menu items but not all from https://electronjs.org/docs/api/menu#main-process

custom electron menu

---

CHANGELOG.md
README.md
package-lock.json
package.json

- Include file diff in merge commits [#1242](https://github.com/FredrikNoren/ungit/pull/1242)
- Hide diff buttons on hover [#1225](https://github.com/FredrikNoren/ungit/pull/1225)
- Publish electron build [#1241](https://github.com/FredrikNoren/ungit/pull/1241)
- Updated Octicons [#1224](https://github.com/FredrikNoren/ungit/pull/1224), [#1245](https://github.com/FredrikNoren/ungit/pull/1245), [#1246](https://github.com/FredrikNoren/ungit/pull/1246)
- Fix stash tooltips [#1227](https://github.com/FredrikNoren/ungit/pull/1227)
- Improve git-init experience [#1228](https://github.com/FredrikNoren/ungit/pull/1228)
- Fix inconsistent diff options [#1229](https://github.com/FredrikNoren/ungit/issues/1229)
- Fix clearing .gitignore [#1236](https://github.com/FredrikNoren/ungit/pull/1236)
- Fix …

Prepare Release 1.5.0

---

.travis.yml
CHANGELOG.md
README.md
appveyor.yml
package.json

It is no longer supported. See https://github.com/FredrikNoren/ungit/pull/1243#issuecomment-549249550
@Hirse: I cherry-picked your commit from the previous PR.

Remove Node 8 from build matrix

---

CHANGELOG.md
source/git-promise.js
test/spec.git-api.diff.js

also show correct commit diffs if same file is currently modified
fixes https://github.com/FredrikNoren/ungit/issues/1124

fix first commit diff

---

components/commit/commit.js
components/commitdiff/commitdiff.html
components/commitdiff/commitdiff.js
components/commitdiff/commitlinediff.js
components/imagediff/imagediff.js
components/staging/staging.js
components/textdiff/textdiff.js
source/git-api.js
source/git-parser.js
source/git-promise.js
test/spec.git-api.branching.js
test/spec.git-api.conflict.js
test/spec.git-api.diff.js
test/spec.git-api.js
test/spec.git-api.submodule.js
test/spec.git-parser.js

Fix diffs not appearing for renamed files

---

CHANGELOG.md
package-lock.json
package.json
source/git-parser.js
test/spec.git-parser.js

Fixes https://github.com/FredrikNoren/ungit/issues/1270

fix gitparser for merge / empty commits

---

Gruntfile.js
package-lock.json
package.json

Remove grunt-plato as plato seems to be no longer maintained: https://github.com/es-analysis/plato

Remove grunt-plato

---

CHANGELOG.md
public/source/server.js

fixes part of https://github.com/FredrikNoren/ungit/issues/1289

Don't show error page when reloading the page

---

package-lock.json
package.json

it was only added to fix it to a working version but it got fixed since then
6ae6242
superseds https://github.com/FredrikNoren/ungit/pull/1299

remove extract-zip dev dependency

---

source/git-promise.js

I haven't debugged this issue in detail yet but want to get CI working again, because we use that to release new versions.
see #1301

use rebase.backend=apply config

---

.github/workflows/ci.yml

Tests did start to fail e.g. https://github.com/FredrikNoren/ungit/actions/runs/86280470

add apt update to github ci

---

components/graph/git-node.js

- Only initialize autocomplete when the search input is shown the first time
- Same for focus-handler, which is currently adding a new one each time
- Fix focus handler to use correct `this` (by using event.target instead)
- Clear search input when selecting from the autocomplete list

Optimizes ref-search autocomplete initialization

---

.github/workflows/ci.yml

setup-node now prints the node and npm version see https://github.com/actions/setup-node/releases/tag/v1.4.2
reference https://github.com/FredrikNoren/ungit/pull/1296#issuecomment-601048594

remove explicit node --version, update upload-artifact

---

components/app/app.html
components/app/app.less
components/app/ungit-plugin.json
components/crash/crash.less
components/crash/ungit-plugin.json
components/graph/graph.html
components/graph/graph.less
components/repository/repository.less
components/staging/staging.less
public/less/generic.less
public/less/styles.less
public/less/variables.less

- Move styles specific to a component from `styles` and `generic` files to component `less` files
- [app](https://github.com/FredrikNoren/ungit/commit/32a0ff5518627dd817fff96443329f4b51416397)
- [crash](https://github.com/FredrikNoren/ungit/commit/8cce359dca116a458585839c35005795b822a2b9)
- [graph](https://github.com/FredrikNoren/ungit/commit/6e873ac7a28d52bafb4b4023eb5ffb61542bb10c)
- [repository](https://github.com/FredrikNoren/ungit/commit/ff7816ef71af34229239f8eeace5568696e9904d)
- [staging](https://github.com/FredrikNoren/ungit/commit/cab2fa0d3a900ec02c665d7a295cb330aaffef6e)
- Remove unused style rules from `generic.less`
- Format `generic.less

Organizes component styles

---

components/staging/staging.less
components/textdiff/textdiff.html
components/textdiff/textdiff.less
components/textdiff/ungit-plugin.json
public/less/styles.less

* Consolidate styles in `textdiff.less`
* Switch button style from `warning` to `default`
* Use actual `<button>` instead of `<span>`

Clean up "Load more"-button

---

components/commit/commit.html
components/commit/commit.less
components/header/header.html
components/header/header.less
components/staging/staging.html
components/staging/staging.less
public/less/generic.less

The only visual change is that the arrows now use the exact color of the container instead of a very close one.

Clean up arrow styling

---

public/less/variables.less

Format and order the variables to be in line with the bootstrap variables file.
This will make future updates and bootstrap upgrades easier.

Format less variables

---

package-lock.json
package.json

Move `dedent` and `superagent` to devDependencies as they are only used it test files.

Move test dependencies to devDependencies

---

public/main.js

The app path is different during debugging vs packaged (asar) so I had to account for that.

set window icon explicitly so it works during debug and on linux

---

components/commit/commit.html
components/commitdiff/commitdiff.html
components/graph/graph.html
components/header/header.html
components/refreshbutton/refreshbutton.html
components/staging/staging.html
components/stash/stash.html
public/source/main.js

Follow up from #1343.
>Yes, following the bootstrap standard `[data-toggle="tooltip"]` selector would be good.
@campersau, @ylecuyer

Use data-toggle to initialize tooltips

---

package.json

I messed this one up last night...

fix messed up merge in package.json

---

.gitignore
.nodemonignore
.npmignore
.prettierignore

This PR cleans up 4 of the existing ignore files (`.gitignore`, `.nodemonignore`, `.npmignore`, and `.prettierignore`). The most important changes are in which files are included in the npm package.
The configuration in this PR removes as many files from the npm package as possible (including for example screenshots and documentation). This is more intended as a starting point to pick which other files to include.
Removed files are
- Component Less and non-bundles JS files
- Common and vendor Less files
- Markdown docs (Plugins and Mergetool)
- Images from Readme
See below for the complete list of which files were and are now included.
In total 99 files, taking about 700kb, are now excluded.
- `.gitignore`
- Only include existing folders and files
- Reorder and add comments
- Add folders …

Clean up ignore files

---

Gruntfile.js
package-lock.json
package.json

using https://www.npmjs.com/package/mocha-parallel-tests
part of https://github.com/FredrikNoren/ungit/issues/895
supersedes #1361

move clickParallel to npm script "clicktest-parallel"

---

.github/workflows/bump.yml
Gruntfile.js
package-lock.json
package.json

using https://www.npmjs.com/package/npm-check-updates
part of https://github.com/FredrikNoren/ungit/issues/895

move bumpdependencies to npm script

---

Gruntfile.js
package.json
scripts/travisnpmpublish.js

basically copy & paste the existing code in separate file.
part of https://github.com/FredrikNoren/ungit/issues/895

move travisnpmpublish to npm scripts

---

README.md

README: add title text to the xkcd image

---

.github/workflows/bump.yml

https://github.com/peter-evans/create-pull-request/blob/master/docs/updating.md#updating-from-v2-to-v3

update peter-evans/create-pull-request to v3

---

CHANGELOG.md
clicktests/environment.js

Use page.waitForTimeout API in tests

---

CHANGELOG.md
components/branches/branches.html
components/branches/branches.js

Fixes https://github.com/FredrikNoren/ungit/issues/1434

Remove listRefsEnabled to be able to check Remote / Branch / Tags again after unchecking all of them

---

CHANGELOG.md
package-lock.json
package.json

- Unhandled rejection ERR_FEATURE_NOT_AVAILABLE_ON_PLATFORM (recursive watch) [#1389](https://github.com/FredrikNoren/ungit/issues/1389)
- Bump Dependencies [#1438](https://github.com/FredrikNoren/ungit/pull/1438)

Prepare version 1.5.13

---

CHANGELOG.md
package-lock.json
package.json
public/source/server.js
source/git-api.js
source/server.js

Breaking changes:
https://github.com/socketio/socket.io-client/releases/tag/3.0.0
https://github.com/socketio/socket.io/releases/tag/3.0.0
Based on #1442

Update socket.io to version 3.0.0

---

bin/ungit
package.json

* run `npm run inspect` to connect to the server with the Chrome Devtools debugger
* show crashes

Script improvements

---

test/.eslintrc.json
test/spec.git-api.js
test/spec.git-api.submodule.js

disable submodule unittests because of git 2.3x changes

---

CHANGELOG.md
package-lock.json
package.json

- simple git flow breaks ungit [#1460](https://github.com/FredrikNoren/ungit/issues/1460)
- Bump Dependencies [#1479](https://github.com/FredrikNoren/ungit/pull/1479)

Prepare version 1.5.18

---

CHANGELOG.md
package-lock.json
package.json

- Fix potential remote code exec [#1510](https://github.com/FredrikNoren/ungit/pull/1510)
- Fix intermittent test failures [#1495](https://github.com/FredrikNoren/ungit/issues/1495)
- lint: small bugs + jsdoc [#1504](https://github.com/FredrikNoren/ungit/pull/1504)
- Bump Dependencies [#1503](https://github.com/FredrikNoren/ungit/pull/1503)
---
@jung-kim Do you think https://github.com/FredrikNoren/ungit/issues/1495 can be closed now?

Prepare version 1.5.20

---

scripts/build.js

Cherry picked @wmertens commit  https://github.com/FredrikNoren/ungit/pull/1527/commits/c2072c36b78e3d90fbba3611f1ff5969e0dccda0

build: fix memory use by building serially

---

components/branches/branches.js
components/commit/commit.js
components/commitdiff/commitdiff.js
components/graph/graph-graphics.html
components/graph/graph.js
components/path/path.js
components/repository/repository.js
components/stash/stash.js
components/submodules/submodules.js
public/source/knockout-bindings.js
public/source/main.js
scripts/build.js
scripts/npmpublish.js
source/config.js
source/git-api.js
source/git-parser.js
source/git-promise.js
source/server.js
source/ungit-plugin.js
test/spec.git-api.ignorefile.js
test/spec.git-parser.js

Extracting some fixes from #1527 and put them into individual commits.
Not included are `tsconfig` and `git-api` changes.

Small fixes and cleanups

---

README.md

This would add in the support for SSH signing of GPG key and closes #1535

Update git version dependency to 2.34.x

---

.github/workflows/ci.yml
appveyor.yml

CI: git allow file protocol which is used in submodule tests

---

CHANGELOG.md
package-lock.json
package.json

- build: fix memory use by building serially [#1529](https://github.com/FredrikNoren/ungit/pull/1529)
- Small fixes and cleanups [#1530](https://github.com/FredrikNoren/ungit/pull/1530)
- Update README.md [#1526](https://github.com/FredrikNoren/ungit/pull/1526)
- Update git version dependency to 2.34.x [#1536](https://github.com/FredrikNoren/ungit/pull/1536)
- Use fork to spawn a new node process [#1537](https://github.com/FredrikNoren/ungit/pull/1537)
- CI: git allow file protocol which is used in submodule tests [#1540](https://github.com/FredrikNoren/ungit/pull/1540)
- Bump Dependencies [#1525](https://github.com/FredrikNoren/ungit/pull/1525), [#1531](https://github.com/FredrikNoren/ungit/pull/1531), [#1533](https://github.com/FredrikNoren/ungit/pull/1533)

Prepare version 1.5.22

---

CHANGELOG.md
package-lock.json
package.json

- Ungit returns 0 when wrong arguments are used [#1548](https://github.com/FredrikNoren/ungit/issues/1548)
- Server process keeps running when parent gets killed [#1552](https://github.com/FredrikNoren/ungit/issues/1552)
- Bump Dependencies [#1542](https://github.com/FredrikNoren/ungit/pull/1542), [#1545](https://github.com/FredrikNoren/ungit/pull/1545), [#1551](https://github.com/FredrikNoren/ungit/pull/1551)

Prepare version 1.5.23

---

CHANGELOG.md
package-lock.json
package.json

- Fallback for font if bundled font dont support glyphs [#1564](https://github.com/FredrikNoren/ungit/pull/1564)
- Bump Dependencies [#1555](https://github.com/FredrikNoren/ungit/pull/1555), [#1559](https://github.com/FredrikNoren/ungit/pull/1559), [#1560](https://github.com/FredrikNoren/ungit/pull/1560), [#1561](https://github.com/FredrikNoren/ungit/pull/1561), [#1563](https://github.com/FredrikNoren/ungit/pull/1563)

Prepare version 1.5.24

---

CHANGELOG.md
package-lock.json
package.json

- Bump Dependencies [#1566](https://github.com/FredrikNoren/ungit/pull/1566), [#1571](https://github.com/FredrikNoren/ungit/pull/1571), [#1574](https://github.com/FredrikNoren/ungit/pull/1574), [#1578](https://github.com/FredrikNoren/ungit/pull/1578)

Prepare version 1.5.25

---

CHANGELOG.md
package-lock.json
package.json

- Bump Dependencies [#1584](https://github.com/FredrikNoren/ungit/pull/1584), [#1585](https://github.com/FredrikNoren/ungit/pull/1585), [#1587](https://github.com/FredrikNoren/ungit/pull/1587), [#1586](https://github.com/FredrikNoren/ungit/pull/1586)

Prepare version 1.5.26

---

components/commit/commit.html
components/commit/commit.js
components/graph/git-node.js
components/header/header.less
source/git-parser.js

Also simplify scroll logic.
Fixes #1581

Show parent commit ids and try to select them on click

---

.github/workflows/ci.yml
components/remotes/remotes.js
source/git-api.js
test/spec.git-api.remote.js

Which got removed in https://github.com/FredrikNoren/ungit/commit/3b8b973e626574789cd3c0524e6b837aa219e5f4
Also make it a GET request like `/remote/*`.

Enable git fetch again

---

.github/workflows/bump.yml
CHANGELOG.md
package-lock.json
package.json

- Enable git fetch again [#1604](https://github.com/FredrikNoren/ungit/pull/1604)
- Bump Dependencies https://github.com/FredrikNoren/ungit/commit/dd9b7a35c92fafc3883a2ad7d04814049e04406a, https://github.com/FredrikNoren/ungit/commit/7e4e830cb71bdcbdd92d903419e1ad5e23a5ddc2, https://github.com/FredrikNoren/ungit/commit/944835dc8627c767c7145dad94b9fb4a2028e685, https://github.com/FredrikNoren/ungit/commit/ea063f47acf1f733b2a0af80d9c94293c3d880b7
- CI Fixes https://github.com/FredrikNoren/ungit/commit/c02db509c2c334e7541e8f3dea4f615c7a614ccb, https://github.com/FredrikNoren/ungit/commit/a32668649836d7fd382574615333807ef3eed370, https://github.com/FredrikNoren/ungit/commit/7349b941a58f95117801fa36029fd44769dee8f8, 
- Replace node 21 with 22 …

Prepare version 1.5.28

---

CHANGELOG.md
README.md

Removed reference to Codiad integration plugin, as Codiad is EOL.

📝 Update README.md
